### ISSUE TITLE
Dendi LLS submission errors

### ISSUE THREAD

**Issue by TaneaY** [CDCgov/prime-reportstream#10525] opened 2023-07-20 01:12 UTC
## **Problem Statement**
Sender receiving errors while submitting the on 7/17 and 7/18

## **What you need to know**
Client has reviewed and mapped the LOINC and equipment ids as per the LIVD tables.
We saw this error , but not sure if it's accurate.

      "field" : "equipment_model_id (equipment_model_id)",
      "message" : "No match found for equipment_model_id (equipment_model_id); please refer to the CDC LIVD table LOINC Mapping spreadsheet for acceptable values.",
      "errorCode" : "INVALID_MSG_EQUIPMENT_MAPPING"

## **Acceptance Criteria**
Confirm equipment model values are accurate

## **To Do**
Review submission for failure

**Comment by sliu1000** [comment] 2023-08-01 23:08
@GilmoreA6 -  Can I close this?
HI James,

Thank you so much for your guidance.

The LOINC code and model [line 1073] didn't match the required LIVD data. We have reached out to the client to make changes. Meanwhile we have submitted all other records successfully.

"id": "bdad8f6b-dd85-4a45-b826-cff0b866b62b",

"submissionId": 24415893,

"overallStatus": "Received",

"timestamp": "2023-07-28T13:45:54.659Z",

"plannedCompletionAt": null,

"actualCompletionAt": null,

"sender": "dendi.default",

"reportItemCount": 1079,




Have a wonderful weekend



Best regards,

Shatabdo Banerjee
Interface Lead
Dendi Inc. 
dendisoftware.com
On Thu, Jul 27, 2023 at 6:35 PM Gilmore, James (CDC/DDPHSS/OD/HITSSU) (CTR) <uaf6@cdc.gov> wrote:
Hi Shatabdo,

Looks like  there was a single row in that file that contained a fatal error. Row 1073 (you can see in the JSON response indicies 1073) had an incorrect value for column "equipment_model_name". I'm not sure what value was in that row as our logs don't show me but it looks like that was the cause.

If you or the lab can't identify the incorrect value you can send me what was in that row for "equipment_model_name" and "test_performed_code" and I can take a look. Please do not send any PHI/PII/identifying information, only the values from those two columns for that row.

Thanks,

James

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by GilmoreA6** [comment] 2023-08-03 15:44
@sliu Yep, go ahead and close

**Closed** 2023-08-03 15:50 UTC
Labels: onboarding-ops, Medium Priority
