### ISSUE TITLE
Fill in sender_id for all senders automatically

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#2145] opened 2021-09-10 15:23 UTC
We need to have the `sender_id` field filled in for all senders in ReportStream so we can start to add them to quality filters. Therefore we're going to check and see if the `sender_id` field is filled in on ingest, and if it is not, we will fill it in automatically.

**Comment by carlosfelix2** [comment] 2021-09-16 13:31
Duplicate of #2146

**Closed by carlosfelix2** 2021-09-16 13:31 UTC
Labels: good first issue, engineering, receiver, sender-pipeline
