### ISSUE TITLE
[PLACEHOLDER] Investigate test failures in CI possibly related to UseOktaMemberships

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#6116] opened 2022-07-14 15:39 UTC
**Describe the bug**
During frontend test suite runs in github actions, the suite intermittently fails early without a test failure or clear warning message. Usually able to resolve by re-running the test suite, though sometimes multiple re-runs are necessary. Unable to reproduce this behavior locally, and as of 7/18 the situation seems to have resolved itself.

**Impact**
Blocking builds until test suite is able to pass.

**To Reproduce**
See https://github.com/CDCgov/prime-reportstream/pull/6121/commits for reference on reproduction and attempts to fix.

Some notes on reproduction, possible causes and possible fixes:

* the fact that tests pass on https://github.com/CDCgov/prime-reportstream/pull/6121/commits/13428ae4a584cc9efd3382b778fc73bbd7822b7b and https://github.com/CDCgov/prime-reportstream/pull/6121/commits/0a0b918d5c64cf5c38dede0276c853ae9a53742b suggest that the problem had to do with the first submissions table test, or the underlying code
* as this failure seems similar to the failures seen during the introduction of `useOktaMemberships`, in which case the underlying issue was inadequately mocked okta interactions, possible that the issue here involved a network connection that was not mocked out within `SubmissionTableWithCursorManager`
* as the issue seems to be fixed as of 7/18 and possibly earlier, another possible reason for the failure could involve the introduction of changes from https://github.com/CDCgov/prime-reportstream/commit/05828a36b263c35af7915f6330165b94ace7104f. It is possible that, if github actions was mistakenly importing the incorrect version of okta js, that type issues could have caused test suite failure, and that by updating our code to be compliant with the latest version of the package may have resolved this. This would point to an issue with how github actions is resolving our package dependency versions. 

**Expected behavior**
Test suite passes on github actions as it does locally

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kevinhaube** [comment] 2022-12-08 21:40
Closing due to no bug reproduction since Summer 2022

**Closed by kevinhaube** 2022-12-08 21:40 UTC
Labels: bug, needs-info, experience, needs-refinement
