### ISSUE TITLE
Engineering changes to website and Okta per content/support needs (Okta)

### ISSUE THREAD

**Issue by Andrey-Glazkv** [CDCgov/prime-reportstream#11074] opened 2023-08-25 13:37 UTC
## Problem statement

We want to implement the necessary changes to the website and Okta system as per the defined content and support needs, including notifications, alert components, user flows, and help pages, so that users experience a smooth transition during the migration and have access to clear information, guidance, and support.

## What you need to know

This will be based on the change requests coming from Design and Content in these tickets:

Revise content of initial email to users (#10537) 
Account creation: Review content style across user flow (#11066)
Revise content of login flow (#10538)
Expired token flow (#11067)
Reset password/forgot username user flow (#11068)
Help page content (#11069)
Alert component content (#11071)
Develop content for website (#11070)

- [Comm plan draft](https://app.box.com/s/snmcejhh9do6yvs39rjac62n1drv691l)
- [Okta flow mural](https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1681921545021/4b0bdcdfb84b03a3a7b0a90741c9dab5c1e3abd6?sender=uc68de765cde7b324bc271858)
- ...

## Acceptance criteria

- [ ] Content and components implemented and published
- [ ] Update the asset logo in the Okta theme (get from Jillian)
- [ ] Update the theme panel with new colors
- [ ] Move legal notice from the alert to the body of the page Login Page
- [ ] Repurpose the alert at the top of the page with the new content on the Login Page
- [ ] Update the content on the password reset alternate flow email
- [ ] Update the content on the password reset normal flow email
- [ ] Update the content of the automated activation email
- [ ] Update content in the "Unable to Sign in" alert in the widget
- [ ] Update remaining content per Figma file
- [ ] Update the ReportStream support page per Content (#11069)

## To do

- [ ] Implementation of content and components (notifications, alert component, help page) in accordance with above requests
- [ ] Alignment with user flow and support needs for resetting passwords, retrieving usernames, handling expired tokens
- [ ] Review with Design/Content team before deployment

**Comment by chris-kuryak** [comment] 2023-09-12 20:57
Duplicate of #10540

**Closed by chris-kuryak** 2023-09-12 20:57 UTC
Labels: experience, needs-refinement, engineering
