### ISSUE TITLE
Design Sender Guide/Documentation

### ISSUE THREAD

**Issue by loripusey** [CDCgov/prime-reportstream#1563] opened 2021-07-12 12:45 UTC
## Problem statement

As a Sender, I would like some instructions to help me register for and use the CSV upload feature in ReportStream because I am either considering using the feature or am having problems using it.

## Acceptance criteria

- We need content and design to provide Senders with the following information
    - Value of the CSV upload feature    
    - How to gain access to the CSV upload feature with a link to the intake form for senders 
   
## To do

- [ ] Content: we need content
- [ ] Design: we need layout for the content

**Comment by HeatherRienks** [comment] 2021-07-12 23:52
@loripusey - this might be a dupe of this issue: https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1579

**Closed** 2021-07-13 12:41 UTC
Labels: Content, Design, sender-tools, website
