### ISSUE TITLE
CO - HL7 Issue from SR Results 8/12/24

### ISSUE THREAD

**Issue by wcollin89** [CDCgov/prime-reportstream#15590] opened 2024-08-13 14:42 UTC
## **Problem Statement**

The ReportStream Support team received an email from CDPHE ELR on 8/12/24 regarding OBX2 and OBX5 issues.

## **What you need to know**

Email text follows:

> This is an automatic email from the CDPHE Electronic Lab Reporting (ELR) system. There was an issue with a file or message submitted by your organization.
> 
> Issue Report: Incorrect HL7 Conformance found in the OBX Segment.
> 
> Message ID: `7f04a816-85dd-431c-8502-7f606315ae7c`
> Received by: CDPHE ELR Onboarding
> Received on: 2024-08-12 10:40:37
> File source: CDC PRIME
> File name: `co-receiver-transform.yml-30eee79c-b9d2-4a00-bd6b-256803001f15-20240812194012.hl7`
> Performing Org Name: High Plains Community Health Center INC
> 
> Please review OBX2 and OBX5 values, correct, and resubmit the file.

## **Acceptance Criteria**
- [ ] Validate issue in OBX2 and OBX5 for these results.
- [ ] Determine steps to resolve - if the user needs to be contacted to resubmit, please advise the Support Team.

## **To Do**

- Check HL7 message to determine the issue with the specified fields and correct.

## **Additional Comments**

The results from the referenced message were submitted as manual entries in SimpleReport, the facility has not uploaded any data via CSV. We are currently unable to access the HL7 files through RS or Metabase.

**Comment by MikaelahD13** [comment] 2024-08-14 13:49
@victor-chaparro may you please take a look and provide guidance?

**Comment by victor-chaparro** [comment] 2024-08-15 18:55
@TaneaY You should be able to download the report by searching for this report id 30eee79c-b9d2-4a00-bd6b-256803001f15 in daily data. I looked at it and don't see any issues with the message. It has a valid OBX2 and OBX5. Did they give any more details on what the issue with those fields is?

**Comment by TaneaY** [comment] 2024-08-15 19:28
@victor-chaparro I was able to download the HL& and noticed most snomed and CLIA numbers formatted correctly even though some messages have more OBX fields then others populated. The OBX2 has populated that symptoms are present without further symptom information for most of the HIGH PLAINS COMMUNITY HEALTH reports. We will reach out to the user and see if there are specific Message ID's related to to this report that they are having issues with. Please take another look to confirm if Support is reviewing the file correctly.

**Comment by TaneaY** [comment] 2024-08-15 19:59
Follow up sent 
Hi Nancy,

We received the following error and want to confirm the Message ID's associated with High Plains Community Health Center INC. Can you please send response with specific Message ID's that are causing this error so that we can investigate further.

Response received:
Here is the full MSH Segment from the file:

MSH|^~\\&|CDC PRIME - Atlanta,^2.16.840.1.114222.4.1.237821^ISO|CDC PRIME^11D2030855^CLIA|CO-ELR|CO|20240812113057||ORU^R01^ORU_R01|7f04a816-85dd-431c-8502-7f606315ae7c|P|2.5.1|||NE|NE|USA|UNICODE UTF-8|ENG^English^ISO||PHLabReport-NoAck^ELR_Receiver^2.16.840.1.113883.9.11^ISO\r

This record was received on the "ONBOARDING" server, not the production server.  

I believe the error was caused by the following OBX segment:
OBX|4|CWE|76691-5^Gender identity^LN^^Gender identity||asked-declined^Asked But Declined||||||F|||20240812111557|06D0899456^High Plains Community Health Center INC^CLIA||||||||High Plains Community Health Center INC^L^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^06D0899456|201 Kendall Dr^^Lamar^CO^81052-3939^USA^^^Prowers||asked-declined^Asked But Declined\r

It is coded as a CWE but then the result value is not a SNOMED triplet.

Nancy

**Comment by victor-chaparro** [comment] 2024-08-20 14:41
@TaneaY I've updated their settings so they will start receiving this instead:
OBX|8|CWE|76691-5^Gender identity^LN^^^^^^Gender identity||ASKU^asked but unknown^NULLFL
Can you confirm if that's ok with them and if we need to resend any messages that had this issue?

**Comment by wcollin89** [comment] 2024-08-20 19:51
@victor-chaparro Thank you! I've reached out to the user with this information and requested feedback.

**Comment by wcollin89** [comment] 2024-08-23 13:07
@victor-chaparro we received the following update from the user this morning:

> I have tried to find a valid SNOMED for the Asked but declined answer and have not had any success.  This report came in through our test server and the code on that server is checking for a valid SNOMED.  This change will result in the same error.  
> 
> Thank you for the work that you put in attempting to fix this, I am sorry that I do not have a solution to offer to you.  Since this came through the test system, there is no need to resend anything.

Thank you!

**Comment by TaneaY** [comment] 2024-09-16 15:31
Closing ticket with above comment

**Closed by TaneaY** 2024-09-16 15:31 UTC
Labels: onboarding-ops, Colorado
