### ISSUE TITLE
Upload new LIVD table

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7952] opened 2023-01-13 15:12 UTC
## Problem statement

The LIVD team sent over a new LIVD table that needs to be uploaded into ReportStream.

## What you need to know

[https://app.zenhub.com/files/304423150/73edc4fc-503a-44dd-a7e2-029b9a6432af/download](https://app.zenhub.com/files/304423150/73edc4fc-503a-44dd-a7e2-029b9a6432af/download)

## To do
 Run livd-table-update command with new table

**Comment by GilmoreA6** [comment] 2023-01-24 21:26
Closed as duplicate of #7956

**Closed** 2023-01-24 21:26 UTC
Labels: onboarding-ops, Medium Priority
