### ISSUE TITLE
Improve secondary navigation for logged-in users

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#4827] opened 2022-03-21 16:00 UTC
## Problem statement

Our current main navigation is getting out of hand! We have several user types who need different things from the navigation, including internal admin users, and it's getting jumbled fast.

## What you need to know

- [Concept 1 in Figma](https://...)
- other concept
- other concept

## Acceptance criteria

- [ ] Investigate several options for secondary navs
- [ ] Outline them in Figma
- [ ] Make a recommendation to go forward with

## To do

- [ ] ...

**Comment by rachelhanster** [comment] 2022-03-28 14:44
@drew-usds Moving this to product backlog. Can you please update figma link (currently broken) and provide more info as this gets refined?

**Comment by a-chappelear** [comment] 2022-08-28 14:29
This is a duplicate of 6160, can this be closed? @drew-usds @HeatherRienks @RakshindaAslam

**Comment by RakshindaAslam** [comment] 2022-08-29 14:12
I believe it can be closed. @drew-usds?

**Closed** 2022-09-01 16:09 UTC
Labels: design, experience
