### ISSUE TITLE
CA - Siskiyou County Test Results Not Getting Into CALRedie

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-reportstream#3976] opened 2022-01-24 23:16 UTC
1/24/2022

Siskiyou Cty reported that some of their test results are not getting into CALRedie. Approximately 30 out of 97 positive results from last week 1/17/22-1/21/22 did not transfer to CalRedie. So looks like some are getting through and some are not. SR team and I troubleshoot with them today and we were unable to pinpoint any issues on the SR side. I am not sure if this was an intermittent issue.

Siskiyou Cty will be sending us a spreadsheet of results that are missing and SR will locate the specimen IDs for RS investigation.

@anshulkumar-usds is there any way to check if there were any NACKs for SR test events between 1/17 - 1/2 for Siskiyou County?

cc - @emmastephenson

**Comment by anshulkumar-usds** [comment] 2022-01-25 14:35
Duplicate - Already being investigated.
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3731

**Comment by anshulkumar-usds** [comment] 2022-01-25 17:16
Correction to last comment: Not a duplicate of the issue above. Needs further investigation.

**Comment by emmastephenson** [comment] 2022-02-08 18:39
@anshulkumar-usds no, the last comment I saw here was the duplicate so I haven't looked into this. I also haven't seen anything from Siskiyou County, not sure if they sent that spreadsheet directly to Ming?

**Comment by anshulkumar-usds** [comment] 2022-02-09 17:27
Will follow up with CA and create new ticket with next steps defined. Closing this for now.

**Closed by anshulkumar-usds** 2022-02-09 17:27 UTC
Labels: onboarding-ops, receiver, data-issue, Medium Priority
