### ISSUE TITLE
Add reusable means to handle pagination, sorting, filtering on API

### ISSUE THREAD

**Issue by luis-pabon-tf** [CDCgov/prime-reportstream#9392] opened 2023-05-04 19:02 UTC
### User Story
As a ReportStream API user, I want to be able to sort, filter and paginate wherever it makes sense.

### Description/Use Case
The [Website API Payload Proposal](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/proposals/0019-website-api-payload-structure.md) requires Pagination, Sorting and Filtering to be implemented wherever it makes sense to use them.

### Risks/Impacts/Considerations
Following his ticket, it may make sense to add a ticket to determine what features each existing and upcoming endpoints need to use.

### Acceptance Criteria
- [ ] A means to handle pagination/sorting/filtering that can be used across different endpoints is available

**Comment by bishoyayoub** [comment] 2023-05-22 15:36
Duplicate of #9404.

**Closed as completed by bishoyayoub** 2023-05-22 15:36 UTC
Labels: pipeline, platform
