### ISSUE TITLE
Revisit org switcher dropdown for admins

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#1519] opened 2021-07-07 15:28 UTC
## Problem statement

The current dropdown didn't go through design/prototyping. It is not a public-facing feature and we frequently demo from our own machines, which could be confusing for folks seeing that feature. As we continue to develop user/settings-type features, that dropdown will also start colliding more with UI elements.

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- ...

## Acceptance criteria

- [ ] Dropdown should either be concealable or otherwise not interfering with the top nav UI

## To do

- [ ] Mockup alternate ideas
- [ ] Test with team
- [ ] Code!

**Comment by jlusds** [comment] 2021-07-19 21:19
duplicate of 1518

**Closed by jlusds** 2021-07-19 21:19 UTC
Labels: Design, receiver, web-receiver
