### ISSUE TITLE
Valueset Editor: Add Legend to Details Page

### ISSUE THREAD

**Issue by sethdarragile6** [CDCgov/prime-reportstream#5910] opened 2022-06-23 23:59 UTC
## Problem statement

Due to some technical complexities and general shortage of time, we passed on implementing the legend for MVP (outlined below from the [design doc](https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=0%3A1)). Implement it now!

![image.png](https://images.zenhubusercontent.com/61688531a0a844ef1cf9286b/9b053178-3a7a-46ff-90f9-003929f71c6e)

The `system`, `reference`, and `referenceUrl` fields will likely have to be pulled via the lookuptable api from the `sender_automation_value_set` table, which is not currently being called from the Details page. Ideally, we would want to have the Lookup Table API Enhancements stories #5707 and #5708 completed in order to make this implementation less "chatty". The `version` part of the legend is redundantly at the Details level already, and should probably be removed.

## What you need to know
- [Valueset Editor Backend Architecture spike](https://cdc-my.sharepoint.com/:w:/g/personal/srz7_cdc_gov/EcT4ehC-ya1HjWqswoF64ksBKooh0wmuth75DY-lCWKeWg?e=2VbYEF)
- Lookup Table API Enhancement stories: #5706 #5707 #5708
- [OG Design Doc](https://www.figma.com/file/fKl2M96ylkxYezwjVVUSIX/Internal-Admin-%26-Tools?node-id=0%3A1)

## Acceptance criteria

- [ ] Implement the legend on the Details page
- [ ] Unit tests as needed

## To do

- [ ] ...

**Comment by bgantick** [comment] 2022-06-24 12:15
Closing: duplicate of #5911

**Closed by bgantick** 2022-06-24 12:15 UTC
Labels: experience, Needs refinement

**Comment by sethdarragile6** [comment] 2022-06-24 21:02
> Closing: duplicate of #5911

Weird! Don't know how that happened
