### ISSUE TITLE
NJ - OBR-25 and OBX-11 Error

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#4427] opened 2022-02-18 04:14 UTC
**Describe the bug**
Please note the errors below in the ELR File: covid-19-772d65a9-bce9-4b3c-8829-b4192cdc42c5-20220217141626.hl7
 
Order: `4279aa7d-6071-42c5-8047-a02f1961bbf9`
 
OBR-25 and OBX-11 are missing.  Please correct and resubmit.

**Comment by oslynn** [comment] 2022-02-28 20:56
Verified with follow:
1.) ./prime data --input-fake 100 --input-schema PrimeDataInput/pdi-covid-19 --output ./junk/pdi-nj-testing.csv --target-states NJ
2.) ./prime data --input junk/pdi-nj-testing.csv --input-schema PrimeDataInput/pdi-covid-19 --output-dir junk --route
3.) Verified OBR-25 and OBX-11
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/d3c996ec-89bc-4582-b277-3ca83e1354ef)
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/54e7e9b6-bc1a-4e74-8664-6809463329c2)

**Comment by oslynn** [comment] 2022-02-28 21:37
@Adrian-Brewster, @anshulkumar-usds.  @jorg3lopez told me simple_report with 'W' for Result Status and our software didn't recognize it.  Therefore, it produces a blank.  Now, @brick-green-agile6 modified code to accept 'W' and it will be ok.  Next, @Adrian-Brewster or @anshulkumar-usds  need to verify with NJ that they can accept OBX-11 with 'W' or not.

**Comment by oslynn** [comment] 2022-03-01 23:55
@jorg3lopez complete this ticket 4427 with ticket 4429.  They are the same problem.

**Comment by anshulkumar-usds** [comment] 2022-03-02 15:45
This is a duplicate of https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4429
Closing this.

**Closed by anshulkumar-usds** 2022-03-02 15:45 UTC
Labels: onboarding-ops, receiver
