### ISSUE TITLE
RI DOH - ELR Failure - Rhode Island

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#7484] opened 2022-11-28 13:45 UTC
Hello @oslynn ,

 

My apologies for the delay in getting this information to you as I was out of the office with the holiday.  On Wed 11/23, RI had an ELR failure for an Intrivo lab that came through ReportStream.  I have asked our vendor to review and this is what they found to be the cause (see below).  If you could investigate this ELR and verify it was supposed to be submitted and/or a test ELR, and if is an actual patient lab and supposed to be submitted to RI, please correct and resubmit.

 

Accession# 123456
Message ID: `7948f368-93e3-43ee-9936-358b4c35d484-3`

![image.png](https://images.zenhubusercontent.com/62827d1e0129e15b5c366b1a/450e2cc7-3623-4982-9280-eed03e417e79)

 

 

InductiveHealth investigation notes:

Hi Jason,

We looked into this, and the lab came from Report Stream/CDCPrime.

The lab failed because OBR-4 was completely missing.

However, we also wanted to point out that there is no patient information in the message except for the patient DOB and the patient city, state, and zip code. There is no patient name, sex, race/ethnicity, or patient street address information. There is also no patient phone number or Ordering Provider information as this was an OTC at home test.

 

 

Thank you in advance,

 

Jason Garrett, BSN, MPH

**Comment by oslynn** [comment] 2022-11-29 13:07
This from message_id = Message ID: 7948f368-93e3-43ee-9936-358b4c35d484.  Note, there is no -3

**Comment by shy2cdc** [comment] 2022-11-29 13:13
Excel table is below with text for both dates and times the same accession was submitted with failure.

 

Processed Time

Status

Message ID

Reporting Facility

Accession#

Exception Text

11/28/22 2:02 PM

Failure

`a345d89e-867b-47e9-b82b-b4aa792d16ae-3`

Intrivo

123456

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

11/23/22 8:05 AM

Failure
`
7948f368-93e3-43ee-9936-358b4c35d484-3`

Intrivo

123456

Error creating lab. Blank identifiers in CE or CWE segments 1 or 4. See Activity Details.

 

 

Thanks,

Jay

**Comment by shy2cdc** [comment] 2022-11-29 16:09
Good Morning Ott and Jason,

This is the first I had time to dig into this further. I have a couple of things below in regards to this specifically that may help us in regards to this potentially.

1. In both of these cases with accession number 123456 it appears this is most likely a generic message that might be being generated that Intrivo is producing as it has most information for the patient as being unknown including the name information and were the exact same message resubmitted the second time. Is this perhaps a test message they may be conducting for some reason?

2. The LOINC Code was not included for the Test that was being conducted in OBR-4.1 and OBR-4.2 and that is why it is failing for the most part.

Message ID's are below for both messages.
7948f368-93e3-43ee-9936-358b4c35d484
a345d89e-867b-47e9-b82b-b4aa792d16ae

Ott if you can look into these 2 issues specifically it would be appreciated.

Thank you,
Jason Suchon

**Comment by oslynn** [comment] 2022-11-29 21:51
The issue is resolved by removing two duplicated test with "TestKit Name ID = 'Flowflex COVID-19 Antigen Home Test_ACON Laboratories, Inc'" from Livd-Suplemental.csv.

**Comment by shy2cdc** [comment] 2022-11-30 14:00
From Jason G. 11/30 8:58am

Hi Ott,

 

These are all coming through with no personal identifiers, ie, names.  RI DOES NOT want any of these at home tests that do not have names, DOBs, or addresses.  These mess up our system greatly.  We have declined these with APHL and CDC prior for the same reason.  Please, do not send these through to RI.

 

Thank you,

Jason

**Comment by oslynn** [comment] 2022-11-30 15:13
I will have to add a quality filter to their production feed.

**Comment by oslynn** [comment] 2022-11-30 21:45
2022-11-30.  To filter our the invalid patient's information, I added to prod and staging database settings.
      qualityFilter:
        - "doesNotMatch(patient_first_name, Unknown)"
        - "doesNotMatch(patient_last_name, Unknown)"
        - "doesNotMatch(patient_dob, Unknown)"

**Closed** 2022-12-01 19:49 UTC
Labels: onboarding-ops, Rhode Island
