### ISSUE TITLE
Implement tags/standard SEO practices

### ISSUE THREAD

**Issue by bgantick** [CDCgov/prime-reportstream#5463] opened 2022-05-12 13:53 UTC
## Problem Statement
We need to add meta tags, schema standards, etc to help with SEO and discoverability of unauthenticated pages.

## What you need to know
From #3181:

> Adding meta/schema tags will help with what shows up in search results and if links are shared via social media/etc.
> From Ming: "can you help me understand why the RS page does not show up when you google it? The RS github page does and is the 2nd highest result behind SimpleReport." https://usds.slack.com/archives/C02HJ43AE8Z/p1635545478124500
> 
> Looks like we have a meta tag defined that prevents robots, like the Google Bot, from crawling the website:
> https://github.com/CDCgov/prime-reportstream/blob/64ac89dfbb71aff56be92617fbdd7bea01cbc425/frontend/src/_includes/head_tags_universal.liquid#L7
> 
> From Ron: "We do need that tag, but it should only be enabled in lower environments."
> 
> We should research what it will take to have marketing pages surface on search engines.

## Acceptance Criteria

- [ ] Every page has basic meta and schema properties
- [ ] Fill out common meta tags (schema.org)
- [ ] Add standard copy for open graph title/description for all unauthenticated pages
- [ ] Add standard open graph img for all unauthenticated pages
- [ ] `robots.txt` is more permissive (for unauthenticated pages)
- [ ] Add a `sitemap.xml` at the root and fill it in with data (this should be automated)

**Comment by sliu1000** [comment] 2022-12-06 19:37
@brandonnava FYI - this looks like something we were talking about add to our site last week.

**Comment by brandonnava** [comment] 2022-12-06 20:19
@sliu1000 Yeah technically this would be on Experience to implement but they will need content from our support FAQ deep dive so will update this once we have those asks for Experience figured out.

**Comment by kevinhaube** [comment] 2022-12-08 21:54
@drew-usds This looks to be a dupe of the other one I tagged you in #3181

**Comment by chris-kuryak** [comment] 2023-01-25 16:05
Old and appears to be duplicate of #3181. Closing.

**Closed by chris-kuryak** 2023-01-25 16:05 UTC
Labels: experience, duplicate
