### ISSUE TITLE
After CSV upload, if you hit back/refresh you get a 404

### ISSUE THREAD

**Issue by drew-usds** [CDCgov/prime-reportstream#3278] opened 2021-12-01 18:07 UTC
**Describe the bug**
Noticed this while doing user testing with A1H - after you complete a successful CSV upload, if the user hits back or refreshes the page it goes to a 404. 

**Impact**
Please describe the impact this bug is causing to your program or organization.

**To Reproduce**
1. Upload a CSV
2. Get to the success page
3. Hit back in your browser
4. See 404

Wasn't able to extensively reproduce, should do more testing to replicate.

**Expected behavior**
Page should keep the success status? Or go back to the upload page?

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bgantick** [comment] 2022-04-15 13:49
Closing: Unable to reproduce. Can re-open if someone comes across this again.

**Closed by bgantick** 2022-04-15 13:49 UTC
Labels: bug, frontend, experience, Needs refinement
