### ISSUE TITLE
IL - OBX-23.1 Org Name truncate to 50 chars

### ISSUE THREAD

**Issue by Adrian-Brewster** [CDCgov/prime-reportstream#3015] opened 2021-11-10 20:03 UTC
Illinois is having a problem with the length of the organization name in OBX 23.1. The maximum character sizing limit for this subfield is 50, and quite often more than 50 characters are being sent.

![image.png](https://images.zenhubusercontent.com/60d1eba7caf0775fd79203f8/19c24e5d-a744-461b-917a-7df14402fc25)

**Comment by mlighdc** [comment] 2021-11-11 00:31
The issue came in on 11/5/21 for tracking purposes.

**Comment by anshulkumar-usds** [comment] 2021-11-12 20:23
@MauriceReeves-usds I remember this ask for at least one other states. Should be truncate OBX-23.1 to 50 chars across the board?

**Comment by anshulkumar-usds** [comment] 2021-11-18 19:40
@jorg3lopez can you please share an update?

**Comment by anshulkumar-usds** [comment] 2021-11-19 15:33
Still working on this. Waiting for deployment on 11/23

**Comment by jorg3lopez** [comment] 2021-11-24 00:16
PR waiting review and approval. It will probably go into production by Tuesday, next week (11/30/2201); unless there is a deployment on Thanksgiving Day.

**Comment by anshulkumar-usds** [comment] 2021-12-02 21:20
@Jorge can you please post an update on this?

**Comment by anshulkumar-usds** [comment] 2021-12-03 14:22
The fix is part of the PR Rick Hawes is working on:
https://github.com/CDCgov/prime-reportstream/pull/3205/commits/0bd1400765107058d8161cd1dce2d7a271bcb4fa

**Comment by anshulkumar-usds** [comment] 2021-12-03 14:25
Will need to wait until deployment on 12/7

**Comment by jorg3lopez** [comment] 2021-12-07 18:47
@anshulkumar-usds Do we have the specimen IDs for the failed messages?

**Comment by Adrian-Brewster** [comment] 2021-12-09 17:51
@jorg3lopez Illinois just received this message where the OBX 23.1 was not truncated. 

OBX|1|CWE|94558-4^SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay^LN^^^^2.68||260415000^Not detected^SCT|||N^Normal (applies to non-numeric results)^HL70078^^^^2.7|||F|||202112091536-0600|26D0044530^Southern Illinois University Edwardsville Student Health Service^CLIA||10811877011290_DIT^BinaxNOW COVID-19 Ag Card^99ELR^^^^2.68^^10811877011290_DIT||202112091551-0600||||Southern Illinois University Edwardsville Student Health Service^^^^^CLIA&2.16.840.1.113883.4.7&ISO^XX^^^26D0044530|58 Circle Drive^Student Success Center Room 0222^Edwardsville^IL^62026^^^^17119

**Comment by anshulkumar-usds** [comment] 2021-12-09 20:58
Per @RickHawesUSDS the fix was deployed on 12/8, but we needed IL's approval to turn this on for them. 
Please enable truncation for OBX-23.1 for IL.

**Comment by anshulkumar-usds** [comment] 2021-12-10 18:53
IL was offered three options, and they selected #1 below:
1. Only receive valid formatted NPI (these will always be 10 digits)
2. Receive both NPIs and unknown provider ids, but truncate the unknown provider ids
3. Receive both NPI and unknown provider ids, do not truncation the unknown provider ids.

If a valid NPI (10 digits) is not available, we need to put in logic to blank out the NPI field completely. fyi - @jorg3lopez

**Comment by jorg3lopez** [comment] 2021-12-10 19:55
@anshulkumar-usds @Adrian-Brewster fix is in production.

**Comment by anshulkumar-usds** [comment] 2021-12-13 14:08
Blocked due to https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3411

**Comment by jorg3lopez** [comment] 2021-12-22 21:16
Test file submitted today. 
File name: 
 test-20211222-covid-19-fb0bc2c7-6faf-4de2-9466-58e6ad0bf2da-20211222174204

**Comment by anshulkumar-usds** [comment] 2021-12-28 14:02
IL was informed of the test file submission. Awaiting feedback.

**Comment by anshulkumar-usds** [comment] 2022-01-03 19:42
IL accepted the test file with fix to OBX-23.1

For MSH-4.1: IL reports that they do not have a limit for this field anymore, so no changes are needed for MSH-4.1. 

@jorg3lopez please advise when the fix is deployed in prod.

**Comment by jorg3lopez** [comment] 2022-01-03 20:29
@anshulkumar-usds changes for OBX-23-1 were pushed to prod a minute ago.

**Comment by jorg3lopez** [comment] 2022-01-03 21:34
Resubmitted files: 
covid-19-fb0bc2c7-6faf-4de2-9466-58e6ad0bf2da-20211222174204

**Comment by anshulkumar-usds** [comment] 2022-01-04 14:40
IL reported back on 1/4 that presence of ampersand is causing additional characters to be included in the messages, and this violating the 50 char limit.

@jorg3lopez

**Comment by anshulkumar-usds** [comment] 2022-01-05 13:57
![image (6).png](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/b8de9fe9-f0b3-4171-ad3e-490312b34af4)

**Comment by anshulkumar-usds** [comment] 2022-01-05 13:57
![image (6).png](https://images.zenhubusercontent.com/607d9d4a591b7cc0bb55c82e/50e72a39-00a3-4d90-af64-f53358d3a3ae)

**Comment by jorg3lopez** [comment] 2022-01-06 00:02
@anshulkumar-usds Working on it.

**Comment by anshulkumar-usds** [comment] 2022-01-21 17:51
1/21: Checking with IL to confirm if they received corrected files.

**Comment by anshulkumar-usds** [comment] 2022-01-23 22:19
@jorg3lopez IL was expecting a .txt extension to the test files. Can you please confirm

**Comment by anshulkumar-usds** [comment] 2022-01-26 15:22
Shared updated files with IL - awaiting response

**Comment by anshulkumar-usds** [comment] 2022-01-26 19:09
IL confirmed the changes made to OBX-23.1 address this issue. They are also requesting same truncation logic be built for ORC-21.1. This work will be documented in a new ticket:
https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4020

**Closed by anshulkumar-usds** 2022-01-26 19:09 UTC
Labels: onboarding-ops, receiver, support, data-issue, Medium Priority
