### ISSUE TITLE
UP Marketing (Q4- 2023)

### ISSUE THREAD

**Issue by LaFreda1** [CDCgov/prime-reportstream#11455] opened 2023-09-21 17:01 UTC
## Problem statement

[Write a short description of what you want to achieve with this task]

## What you need to know

 [Links to documents, workflows, or list of key people and contact info]

- [Document 1](https://...)
- [Document 2](https://...)
- ...

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by brandonnava** [comment] 2023-09-21 17:16
Closing as dupe of marketing effort here: https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10156

**Closed by brandonnava** 2023-09-21 17:16 UTC
Labels: onboarding-ops, Epic
