### ISSUE TITLE
Upload new LIVD table

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#7956] opened 2023-01-13 17:03 UTC
## Problem statement

The LIVD team sent over a new LIVD table that needs to be uploaded into ReportStream.

## What you need to know

[https://app.zenhub.com/files/304423150/fd0852c2-aa70-4e42-8d2f-e18f4ae04bfe/download](https://app.zenhub.com/files/304423150/fd0852c2-aa70-4e42-8d2f-e18f4ae04bfe/download)

### To do

Run livd-table-update command with new table

**Comment by brandonnava** [comment] 2023-01-17 16:24
Closed as duplicate of #7952

**Comment by GilmoreA6** [comment] 2023-01-24 21:26
Re-opening as this is the correct file with the additional columns.

**Comment by GilmoreA6** [comment] 2023-01-24 21:27
[https://app.zenhub.com/files/304423150/3ea41f50-b8e9-4b19-b15b-b3f70ed02a0f/download](https://app.zenhub.com/files/304423150/3ea41f50-b8e9-4b19-b15b-b3f70ed02a0f/download)

**Comment by GilmoreA6** [comment] 2023-01-24 22:37
Waiting for issues with Staging to be resolved.

**Closed** 2023-01-31 19:45 UTC
Labels: onboarding-ops
