### ISSUE TITLE
Updated Quick Test to Show Error Type and Message

### ISSUE THREAD

**Issue by MauriceReeves-usds** [CDCgov/prime-reportstream#1485] opened 2021-07-06 16:11 UTC
Today I was encountering issues while trying to run the end2end test that looked like credential errors. I attempted to save credentials for the different receivers and organizations it continued to fail. Looking deeper at the error, the IGNORE organizations were transferred to the `DEFAULT-SFTP` credential. If the `end2end` test showed what the error messages was that caused the failure, it could save some cycles.

**Comment by jimduff-usds** [comment] 2022-01-21 19:56
Its true that to find these the cause of a downstream Smoke test error you have to look in the ReportStream docker logs, which is a pain.  But I don't see a great answer for that.  Haven't seen this occur in a while, so I'm closing it.  Feel free to open if you disagree.

**Closed by jimduff-usds** 2022-01-21 19:56 UTC
Labels: pipeline
