### ISSUE TITLE
Reduce errors and improve sender and receiver visibility for fields currently used and populated by the LivdMapper()

### ISSUE THREAD

**Issue by MikeC-A6** [CDCgov/prime-reportstream#2957] opened 2021-11-06 14:41 UTC
There have been multiple issues created since May, 2021 related to fields used and populated by the LivdMapper().  This Epic will consolidate those issues and create new user stories and acceptance criteria for the issues to be addressed.

**Problem Summary:**

If a sender does not send in the _exact_ Model_ID or Test_Kit_Name_ID, multiple fields will fail to populate in the outbound file to the STLT.  Importantly, even if the Test_Performed_LOINC_CODE is supplied by the sender, this value will be overwritten with a blank in the outbound file to the STLT if the Model_ID or Test_Kit_Name_ID is incorrect (i.e. the sender missed an asterisk in the string name).  The Test_Performed_LOINC_Code is a critical value for STLTs, as many use that value for routing records from their Rhapsody integration engine to the correct disease surveillance system or module within that STLT. This issue appears to have affected over 266,000 records received between September 19th and November 5, 2021. STLTs have reported ongoing issues with not receiving LOINC codes, and is a driver of ongoing tickets received by the Onboarding and Operations Team.

Based on the attached analysis, there appears to be some simple fixes that will address the majority of the records which are failing to populate a LOINC code.  Specifically, 99.75% of the records that had an incorrect Model_ID or Test_Kit_Name_ID between 9/19 and 11/5 we only off by an asterisk (the sender added an asterisk unnecessarily, or didn't include an asterisk at the end of the test name when it should have).
https://app.zenhub.com/files/304423150/33c3d86b-8e8c-41bb-8384-5439a97db74f/download

**Original Related issues**:
https://github.com/CDCgov/prime-reportstream/issues/1192
https://github.com/CDCgov/prime-reportstream/issues/1688
https://github.com/CDCgov/prime-reportstream/issues/2635
https://github.com/CDCgov/prime-reportstream/issues/2800

**Comment by carlosfelix2** [comment] 2021-12-20 14:43
Duplicate of #3173

**Closed by carlosfelix2** 2021-12-20 14:43 UTC
Labels: bug, Epic, High Priority, data-issue
