### ISSUE TITLE
Look into Results Spike and High NJ/NY Failure Rate

### ISSUE THREAD

**Issue by brandonnava** [CDCgov/prime-reportstream#10286] opened 2023-07-05 15:19 UTC
![Screen Shot 2023-07-05 at 8.04.39 AM.png](https://images.zenhubusercontent.com/6349a3f54b09e7bf98f8a909/a0cf326d-7701-4817-be41-c77ec8086509)

Screenshot showing the spike in test results and the high failure rate for NY and NJ. The goal is to know what happened and why.

**Comment by oslynn** [comment] 2023-07-10 14:20
According to information from @GilmoreA6, simple_report resubmitted a lot of messages to NJ/NY.  That was the cause of spike.  I am closing this ticket.

**Closed by oslynn** 2023-07-10 14:20 UTC
Labels: bug, onboarding-ops, New Jersey, New York
