### ISSUE TITLE
MA - Staging Error (MA-PHD--ELR-SECONDARY)

### ISSUE THREAD

**Issue by sliu1000** [CDCgov/prime-reportstream#7939] opened 2023-01-12 00:22 UTC
## Problem statement

Staging error - manual intervention required.

## What you need to know

[1;31m21:10:28.600 [pool-2-thread-57][152] FATAL-ALERT gov.cdc.prime.router.azure.SendFunction - FAILED Sftp upload of inputReportId bac9f313-d4e5-4f5b-90b8-de94850e489e to SFTPTransportType(host=172.17.6.20, port=22, filePath=./upload, credentialName=null) (orgService = ma-phd.elr-secondary), Exception: Status code 404, '{'error':{'code':'SecretNotFound','message':'A secret with (name/id) MA-PHD--ELR-SECONDARY was not found in this key vault. If you recently deleted this secret you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182'}}', All retries failed.  Manual Intervention Required.  Send Error report for: bac9f313-d4e5-4f5b-90b8-de94850e489e to ma-phd.elr-secondary[m

## To do

- Engineer please investigate

**Comment by LaFreda1** [comment] 2023-06-01 22:18
@sliu1000 Any context on this ticket? I see that it was initially assigned to platform...any reason for that?

**Comment by jalbinson** [comment] 2023-06-02 18:02
Discussed this with @GilmoreA6 and it turns out there was a point in which the receiver settings for "elr-secondary" were set up for a potential integration test while there was a jurisdictional filter that allowed the sending of reports. There was never any credential associated with MA-PHD on staging by design. This has already been fixed but updating the jurisdictional filter to "allowNone" for this receiver so this shouldn't happen again.

**Closed by jalbinson** 2023-06-02 18:02 UTC
Labels: onboarding-ops
