### ISSUE TITLE
FHIRPath examining State throws exception when State missing in actual data

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-reportstream#8583] opened 2023-03-03 14:33 UTC
## User Story:
As a sender of data, I should not be forced to include fields/resources in my messages if there is no validation in ReportStream. If ReportStream cannot route a message because a filter FHIR query fails due to my message missing the resource(s), the application should NOT throw an exception and instead just simply not route the message. 

## Description/Use Case
I may be wrong, but I suspect FHIR paths like  `%performerState = 'IG' or %patientState = 'IG'` path needs to be improved to automatically check for whether the path even exists, before checking whether the values match.

We have no control over the data outsiders are sending us, so it won't be unusual to get data with key fields missing.   In the above case, it should simply not route the data to that receiver, since there's no State info in the data.  This isn't an error.

## Steps to reproduce

I submitted this FHIR to the U.P.:    https://github.com/CDCgov/trusted-intermediary/blob/a35a6f55a5c8fd18f9cfda0cf75bf0e39e2b08c4/examples/fhir/lab_order.json

by doing this:
- Put the FHIR into a file called peter-mar3.fhir
- Collapse it to ndjson:  `tr '\n' ' ' < peter-mar3.fhir > peter-mar3.ndjson`
- submit it:  `curl -X POST -H "client:jimtest.etor-service-sender" -H "Content-Type: application/fhir+ndjson" --data-binary "@./src/testIntegration/resources/datatests/HL7_to_FHIR/jim_sample_co_1_20220518-0001.fhir"  "http://localhost:7071/api/reports"`
- (I think you could use any UP client)

You'll get this exception in the RS logs:

```
[2023-03-03T14:05:45.061Z] 09:05:45.061 [pool-2-thread-270][2287] ERROR gov.cdc.prime.router.fhirengine.translation.hl7.utils.FhirPathUtils - FHIR Path expression did not evaluate to a boolean type: %performerState = 'IG' or %patientState = 'IG'
[2023-03-03T14:05:45.061Z] gov.cdc.prime.router.fhirengine.translation.hl7.SchemaException: FHIR Path expression did not evaluate to a boolean type: %performerState = 'IG' or %patientState = 'IG'
[2023-03-03T14:05:45.061Z]      at gov.cdc.prime.router.fhirengine.translation.hl7.utils.FhirPathUtils.evaluateCondition(FhirPathUtils.kt:103) ~[prime-router-0.2-SNAPSHOT.jar:?]
[2023-03-03T14:05:45.061Z]      at gov.cdc.prime.router.fhirengine.engine.FHIRRouter.evaluateFilterCondition$prime_router(FHIRRouter.kt:446) ~[prime-router-0.2-SNAPSHOT.jar:?]
[2023-03-03T14:05:45.061Z]      at gov.cdc.prime.router.fhirengine.engine.FHIRRouter.evaluateFilterCondition$prime_router$default(FHIRRouter.kt:434) ~[prime-router-0.2-SNAPSHOT.jar:?]
[2023-03-03T14:05:45.061Z]      at gov.cdc.prime.router.fhirengine.engine.FHIRRouter.applyFilters$prime_router(FHIRRouter.kt:346) ~[prime-router-0.2-SNAPSHOT.jar:?]
[2023-03-03T14:05:45.061Z]      at gov.cdc.prime.router.fhirengine.engine.FHIRRouter.doWork(FHIRRouter.kt:186) ~[prime-router-0.2-SNAPSHOT.jar:?]
[2023-03-03T14:05:45.061Z]      at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.doRoute$prime_router(FHIRFunctions.kt:91) ~[prime-router-0.2-SNAPSHOT.jar:?]
[2023-03-03T14:05:45.061Z]      at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.doRoute$prime_router$default(FHIRFunctions.kt:82) ~[prime-router-0.2-SNAPSHOT.jar:?]
[2023-03-03T14:05:45.061Z]      at gov.cdc.prime.router.fhirengine.azure.FHIRFunctions.route(FHIRFunctions.kt:73) ~[prime-router-0.2-SNAPSHOT.jar:?]

```

Note:  If I submit one of our own FHIR bundles (exact same curl as above, except change the file) then I do NOT get that exception.

## Expected behavior

If the data does not contain enough info to make a routing decision based on a particular predicate, the UP should simply not route the data to that receiver.    This is not an error.

## Acceptance Criteria
- [ ] RS does not throw an exception when a filter check fails due to FHIR query failing.

**Comment by arnejduranovic** [comment] 2023-03-13 18:47
Duplicate of #8552?

**Comment by arnejduranovic** [comment] 2023-03-13 19:25
Once Validation and Transformation functionality is implemented, this will no longer be an issue. Will defer for permanent solution. See solution to https://github.com/CDCgov/prime-reportstream/issues/8552 for immediate solution.

**Closed by arnejduranovic** 2023-03-13 19:25 UTC
Labels: pipeline, platform, etor, etor-mvp
