### ISSUE TITLE
CA - Transmission Errors

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#8185] opened 2023-02-03 21:59 UTC
## Problem statement

During our monthly check-in with California.  They mentioned an issue for Fresno County.  They noticed that the dates being reported through CDC ReportStream/SimpleReport appear incorrectly on CALREDIE.

Also, Incidents do not make it to Fresno County even though patient has a Fresno County address.  In conclusion, missing Incidents when checking received vs sent cases.

##Background Information

 Here are some examples of the date uplift issue that Fresno County was noticing. I’m attaching their list of a subset of the affected accessions, and including here in the email body two examples they sent with full details. Please let me know if you need more info!

 ![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/1c141479-12f1-468b-80ef-a4acd0670e12)

**Comment by Jcavallo7** [comment] 2023-02-15 18:25
*update from user*

Morning! Just wanted to do a quick check on this ticket, see if it had moved up much in the queue yet.

 

Thanks!

**Comment by Jcavallo7** [comment] 2023-02-28 17:26
*update from user* 

Hello all! Just wanted to check in on this, see if we were any closer to research/resolution. Thanks!

**Comment by LaFreda1** [comment] 2023-03-07 17:49
@brick-green do we have an update for Teddy? It can be small :) I just want to provide something

**Comment by brick-green** [comment] 2023-03-08 21:51
@LaFreda1 Unfortunately this data has passed the 60day mark and has been purged from the system. So I can't verify the issue. I'm also a bit confused because there are multiple accession numbers referenced in the screenshots. Can we check with CA to see if this issue is ongoing with more recent examples?

**Comment by LaFreda1** [comment] 2023-03-09 18:53
Hi Teddy, 
Thanks for clarifying! Unfortunately, the information for ticket #8185 has been deleted from the system since it was out of date by 60 days. In the screenshot provided (see below), there are multiple ascension numbers referenced. Will you clarify where the issue lies? Have you experienced this issue recently? If so, will you provide those screenshots? Thanks!
image.png



Best,
LaFreda

**Comment by brick-green** [comment] 2023-03-10 23:06
It's true that we don't have the accessions CA referenced. But I did just make a test file and confirmed the behavior described. So I can work with what I have.

**Comment by LaFreda1** [comment] 2023-03-13 16:49
Sent eon 3/13/23:

Hi Teddy, 
Happy Monday! We do not have the ascensions referenced in the screenshot. Brick made a test file this morning and confirmed the described behavior, so he can work on this issue with these data. I will update you as soon as he makes progress on it. 





Best,
LaFreda

**Comment by LaFreda1** [comment] 2023-03-13 16:56
Lovely, thank so much for the update LaFreda!

**Comment by brick-green** [comment] 2023-03-15 18:09
Found the issue. It's in the DateUtilities. When we receive a date from a sender in a field with type datetime, we are zeroing out the time and offset. Then when it goes to a receiver that wants that dates in local time the conversion to local is pushing the date back a day because it thinks the time is midnight UTC.

**Comment by LaFreda1** [comment] 2023-03-15 18:12
@brick-green Got it! I will send this update to Teddy. Is this an easy fix? Will we just stop zeroing out the time and offset?

**Comment by brick-green** [comment] 2023-03-15 18:20
It's not too difficult of a fix. Hopeful to have it ready for next thursday's deploy. The fix will be to ignore dates that come in with zero'd out time and offset so that the system doesn't try to convert them to the local time for the jurisdiction.

**Comment by LaFreda1** [comment] 2023-03-22 17:39
@brick-green Will this be ready for deployment tomorrow?

**Comment by brick-green** [comment] 2023-03-28 14:43
code has been merged and included in the deploy for today(3/28)

**Comment by brick-green** [comment] 2023-03-29 16:41
Code has been deployed. I will talk to teddy about this then close the ticket

**Closed** 2023-04-21 14:15 UTC
Labels: onboarding-ops, Medium Priority, California
