### ISSUE TITLE
InBios Intl - Message Validation

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#7203] opened 2022-11-02 14:06 UTC
Hello,

User states: 
Hello, 

We are beginning to conduct formal validations for the reporting feature on our app and wanted to validate the transmission going from our App to ReportStream is validated. 

We’ve submitted 3 entries and needed help to validate these entries or conversely share a csv file for the three IDs so we can manually verify the information ReportStream has received is correct. 

Test ID
* `25ffa2ff-de8b-43a1-b4cb-6d2fa0018cf7`
* `8eb1d891-ab06-4549-b8a0-2397ee3eac1f`
*` 8a9d00df-4952-498d-b14a-d954daaf9862`

User is based out of WA and their organization is InBios International Inc.

User's name is Vik Bohra.

**Comment by sliu1000** [comment] 2022-11-16 15:53
@BerniXiongA6 @brandonnava 

Did we schedule a Kickoff meeting for this sender? Should I request some times?

**Comment by BerniXiongA6** [comment] 2022-11-16 15:58
Hi @sliu1000 I can reach out to them since we’ve changed up our sender kickoff process slightly. Thanks for the reminder! cc: @brandonnava

**Comment by shy2cdc** [comment] 2022-11-16 17:37
Email from James:

Hi Sharon,

Yes, we already had a kickoff meeting some time ago with Anshul Kumar and Joel Biskie; we did some initial data verification with them as well and that was successful.  They subsequently provided the key and server information for the production server.

 

However, for this product, we had to go through clinical trials and this delayed implementation of the actual reporting feature.  As part of the formal software validation process, we need to verify that this “final product” data that we are sending to your servers is “matching” to the expected information.  (Not just receiving the successful ‘ping’ from the server.) Please let me know if there’s anything else we need to clarify??  Is it possible for Vik to get the information / data he requested as part of the validation process?? 

 

Thanks!

-James

**Comment by brandonnava** [comment] 2022-11-16 17:41
@BerniXiongA6 Sounds like they need a kickoff? Or would James or Brick emailing them be enough?

**Comment by BerniXiongA6** [comment] 2022-11-17 16:30
Hey @sliu1000 @brandonnava I can send them new sender kickoff materials and then I'll propose times to schedule in Decembrer with them. Will udpate this ticket when I send out the email. Thanks!

**Comment by BerniXiongA6** [comment] 2022-11-25 15:03
BX sent email to sender on 11/25:

> Hello Vik,
> 
> Thanks for your reply. Since we've updated our Programmer's Guide within the last few months, please review the guide to make sure your test file follows the list of field requirements for the COVID-19 schema. If your test files were created with the programmer's guide prior to Version August 2022, please generate a new test file and reply to all here with a new test file.
> 
> Our current backlog is about 3 to 4 weeks; therefore, the soonest we'll be able to accept another data sender into our queue is in mid-December. Please stand by and we'll let you know when your ticket has been assigned to an onboarding engineer. In the mean time, you can email your new test file (if needed) anytime before then.
> 
> Thank you so much.
> 
> Best,
> Berni
> 


Email received from sender on 11/23/2022:

> From: Vik Bohra <v.bohra@Inbios.com>
> Sent: Wednesday, November 23, 2022 4:50 PM
>  
> Hello Berni,
> 
>  
> 
> Very nice to meet you! Your right, our team has engaged previously with Report Stream team (Anshul Kumar and Joel Biskie); where we did initial data verification with them, which was successful. They subsequently provided the key and server information for the production server.
> 
>  
> 
> However, for this product, we had to go through clinical trials and this delayed implementation of the actual reporting feature.  As part of the formal software validation process, we need to verify that this “final product” data that we are sending to your servers is “matching” to the expected information.  (Not just receiving the successful ‘201’ status from the server.)
> 
>  
> 
> At this point, we don’t require a kick-off meeting. We are just looking for you to provide us the information / data where we can validate what Report Stream received is indeed what we sent across as part of our validation process. The first attachment includes csv files of three patients with non-PII data which we sent on November 1st. Could you confirm what you received for these entries on your end and share the respective csv files so we can compare and confirm they are matching the values. Please let me know what you think.
> 
>  
> 
> Looking forward to working with you. Thanks!
> 
>  
> 
> Regards,
> 
> Vik
> 

 
Email sent from BX to sender on 11/22/2022:

> Hi Vik:
> 
>  
> 
> Thank you for your interest in getting started with ReportStream. It appears you may have worked with a previous team member a while back. I'm the Delivery Manager for our Onboarding Team at ReportStream, and I'll be happy to assist you at this time.
> 
> 
> 
> 
> Since it has been a bit, some of our processes have changed. The next step is to get you acclimated to how ReportStream works and our current onboarding process for data senders. I'm sharing some useful onboarding resources in the following that you can preview ahead of scheduling a kick-off session with our technical team: 
> 
> 1. Watch this 5-minute video to see the kick-off presentation on ReportStream for data senders (click to download MP4)  
> 
> 2. Review the accompanying transcript, which includes mentioned resource links (click to download PDF)   
> 
> 3. Preview the Programmer’s Guide (which is also mentioned in the transcript above) ahead of scheduling a Sender Kick-Off session with our technical team. 
> 
> 4. Schedule your Sender Kick-Off session with our technical team by replying to this email. We’ll offer a few time slots in which our technical team member/s will be available to meet with you by video call for 30 minutes to answer specific questions you have about technical requirements, etc. 
> 
> 
> 
> 
> Please note that onboarding officially begins when ReportStream starts the “test file validation” process with your team (which is mentioned in the programmer’s guide above). With our current backlog, the soonest we’re able to onboard new data senders is mid-late December timeframe.  
> 
> 
> 
> 
> We look forward to assisting you.
> 
>  
> 
> Thank you.  
> 
>  Berni
> 
>  
> 
>

**Comment by BerniXiongA6** [comment] 2022-11-25 19:51
Any engineer can assign themselves to validate this sender's files once the Sender has confirmed their test files are using the most current API fields list. cc: @brandonnava @brick-green @sliu1000

**Comment by Jcavallo7** [comment] 2022-12-01 00:39
Hello, 

User has come back with an updated inquiry. 

"Since we are conducting csv implementation, do we need to include every field in our implementation which is marked as “(OTC)” in the csv column name?"

**Comment by GilmoreA6** [comment] 2022-12-02 23:05
Hi Vik,

My name is James Gilmore and I will be working with you on onboarding InBios to ReportStream. I saw you had some questions re: the format and wanted to make sure to answer those for you here:

Our product is for OTC purposes only, as such, we don’t expect to have values for many fields which are marked as “(OTC)” in CSV Column Names. Specifically, fields in the “Order and Result Data Elements” & “Ordering Provider Data Elements” sections which cannot be blank. So would it be okay to send a value of “OTC” for these fields?
For the columns marked "OTC" we do need all columns marked this way to be present in the file. Some of these columns may not need to contain data but the columns are required otherwise the file will fail. In the "order and result data elements" , there are some columns which indicate in the additional guidance section that they can be defaulted for OTC. For example, the "specimen_collection_date" if unknown can be populated with the order_test_date. Similarly, "testing_lab_specimen_received_date" can be populated with "order_test_date". For the provider information fields, these can be left blank for OTC, we will populate them with a default value signifying they are OTC. I apologize as the guide is unclear about this.
Is there a preferred order for the csv column headers when they are shared with ReportStream or can they be in any order as long as the column header names match with what’s indicated in the ReportStream document?
They can be in any order as long as they are present
In the sample csv file from website (link), a) this was dated from May, 2022 – wanted to check if there was a more update to date version or if we are good to use this, and b) the “accession_number” field for the first two patients is empty but the document indicates it’s a field which cannot be blank and will fail the submission – so was wondering if this was by mistake left as blank?
This example is not specifically related to OTC data but is a good general example. Accession_id is a required field, however some of our OTC senders were unable to produce a unique id so if the field is blank RS will create a unique id by combining the patient_id + incrementing value + current date.
Also is it necessary to provide “patient_county” if “patient_zip_code” is being collected & shared with ReportStream?
Yes, since there is overlap between zip codes and counties, zip code is not sufficient to identify a patient's county. ReportStream does route data to county level public health jurisdictions and needs this information for routing.
Since we are conducting csv implementation, do we need to include every field in our implementation which is marked as “(OTC)” in the csv column name?
See answer to question one. All columns need to be present but not every field in every row needs to contain data to successfully transmit the report.

Let me know if you have any other questions I can answer. Additionally, we are piloting a self validation service that is not yet available publicly. If you would be willing, once you have some example files ready, we would love to schedule a 30-45 minute meeting to get your thoughts on the validator. If this is something you would be willing to do please let me know and we will get something scheduled.

Thanks,

James

James Gilmore (Agile Six)
Senior HL7 Data Analyst
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by sliu1000** [comment] 2022-12-06 18:01
Additional Questions from Sender:

Hi James –

 

Thank you for the prompt response!

 

Here are a couple of additional questions:

As you indicated below, the guide does require a few updates so clarify any confusion. So, for the fields which are not required (i.e., patient_phone_number, patient_city, patient_street, etc.) but cannot have a blank value – is there a recommended value we can set them to? For ex. “Unknown / Not Provided”
And for all “order_provider_*” fields à we will just leave these fields as blank per your guidance below.
Can you confirm the recommended values would be okay for the following fields in the table?
 
![image.png](https://images.zenhubusercontent.com/6282728600f2331155d73bf3/61b92e86-35d6-4a5b-837e-9ab2f81bc0af)

“test_result_status” field indicates it to be a required field in the programmer’s guide but on the website: https://reportstream.cdc.gov/resources/csv-schema#ordering-facility it shows it to be an optional field. Could you help clarify which it is?
 

We’d be happy to partner with you on the self-validation service. I will keep you posted on our progress on getting you a sample test file (likely by end of next week) and similarly will continue to reach out for any other follow-up questions I may have. Your responses below helped tremendously. Thank you again
 

Regards,

**Comment by sliu1000** [comment] 2022-12-20 16:26
Update from Sender:

Hello James,

Hope all is well.

[https://app.zenhub.com/files/304423150/51cf0b41-5ce2-436d-9ffc-c98cb2c39c90/download]
Apologies on the delay as it took a bit longer than we anticipated. We had to complete our implementation and validate the changes to ensure our csv format and data was all accurate before we were ready to share it for review. I’m happy to say that we appear to be at a good point based on all the feedback you provided below and would like to share our first patient csv file with dummy/simulated data, please see attached. Please review and let us know what changes or modifications we need to make to ensure we can send these results to ReportStream moving forward as OTC.

Also, happy to engage this week if you are available to discuss the self-validation service, and if not, we can touch base at the beginning of the year as well. Please let me know what best works.  

 

Look forward to your updates on this.

 

Thanks & Happy Holidays!

Regards,

Vik

**Comment by GilmoreA6** [comment] 2022-12-31 00:36
Hi James,

 

Great, thank you for the feedback here. We will get these addressed and share an updated csv file very soon.

 

Happy Holidays and Happy New Year!

 

Regards,

**Comment by GilmoreA6** [comment] 2022-12-31 00:37
Provided feedback and asked for 2nd round of modifications

**Comment by sliu1000** [comment] 2023-01-10 23:00
@GilmoreA6 

Vik from Inbios has sent another sample for your review.  Please let me know if you'd like me to forward the email to you. However, I believe you should have been cc'd.

Best regards,

Sharon

**Comment by rnz6** [comment] 2023-01-17 17:55
Update from Sender:

@GilmoreA6 

Hi ReportStream Team, James,
 
Following up here to see if there was any additional feedback you or the team had from the preliminary/draft report we shared. Please let me know. Thank you!

Regards,
Vik

**Comment by GilmoreA6** [comment] 2023-01-17 18:30
Hi Vik,

Can you send another test file to staging (please make sure it is fake data)? I had to make an adjustment on our side to your schema in staging. Other than that the file looks good.

Thanks,

James

**Closed** 2023-01-17 19:21 UTC
Labels: onboarding-ops, sender, Medium Priority
