### ISSUE TITLE
Document process for solving the Poison Queue issue from 11/6/2023

### ISSUE THREAD

**Issue by chris-kuryak** [CDCgov/prime-reportstream#12144] opened 2023-11-07 18:56 UTC
## Problem statement

A Poison Queue issue arose 11/6/2023 flagged by DevOps and investigated/solved by James. The process for investigating and solving that issue needs to be documented.

## What you need to know

TBD

## Acceptance criteria

- [ ] Process documented, resolution documented
- [ ] Documentation saved in a location accessible by all other engineers on RS (work with Victor to determine)

**Comment by GilmoreA6** [comment] 2023-11-21 16:52
Closing as duplicate of #12264

**Closed by GilmoreA6** 2023-11-21 16:52 UTC
Labels: onboarding-ops, needs-refinement, engineering
