### ISSUE TITLE
Normal users are not able to make settings read calls for their organizations

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-reportstream#976] opened 2021-05-01 00:25 UTC
**Describe the bug**
Authentication of normal org users is broken. 

**Impact**
This bug prevents the web receiver launch

**To Reproduce**
1. Create a user in a PHD user group like DHaz_phd
2. ./prime login
3. ./prime organization get --env staging --name az-phd
4. Authorization error

**Expected behavior**
No auth error as the get of setting is authorized. Updates are not.

**Comment by oslynn** [comment] 2022-03-24 22:38
I can't reproduce this issue.Ott.Sathngam-A@MacBook-Pro prime-router % ./prime login
No need to login in this environment
Ott.Sathngam-A@MacBook-Pro prime-router % ./prime login --env staging
About to launch a browser to log in to Okta...
Login valid until 2022-03-24T18:30:55.328496
Ott.Sathngam-A@MacBook-Pro prime-router % ./prime organization get --env staging --name az-phd
---
name: “az-phd”
description: “Arizona PHD”
jurisdiction: “STATE”
stateCode: “AZ”
countyName: null
filters: null
meta:
 version: 1
 createdBy: “jbiskie@flexion.us”
 createdAt: “2021-12-22T21:39:57.01501Z”

**Comment by oslynn** [comment] 2022-03-25 19:07
@jorg3lopez and @oslynn were try to reproduce the issue and can't be able to reproduce.  We think the issue is already fixed.  This is an old ticket opened at Apr 30, 2021.  Following is screenshot of trying to reproduce the issue:
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/79c40816-95fe-4968-94f0-21ce46a449f7)

**Comment by Adrian-Brewster** [comment] 2022-03-28 15:28
Unable to reproduce.  Closing out.

**Closed by Adrian-Brewster** 2022-03-28 15:28 UTC
Labels: bug, onboarding-ops
