### ISSUE TITLE
Preflight check API parameters and limit number of rows returned by API queries

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-reportstream#6303] opened 2022-08-03 18:15 UTC
May API calls allow a date range (or offset + page size) to determine the size of the data return. This can be abused (often unintentionally) to query and return an unbounded amount of data.

API and Database calls should limit sizes.

- At the API level, if any parameters can very data size returned (page size, date range), then they should be sanity checked and return an error `413 Payload Too Large`. 
- ALL db calls accessible from APIs should include a `.limit(MAX_RECORDS_TO_RETURN)` to set an upper bounds on rows returned from a query. This is a safety fallback if some API call doesn't have the check.

**TODO**
> _List all APIs as a checklist to verify. Ticket may need to be an epic?_

- [ ] `adm/getsendfailures` 
    (Issue #6304 - tomn)
- [ ] `adm/listreceiversconnstatus`
    (Issue #6304 - tomn)
- [ ] _..._

**Comment by bishoyayoub** [comment] 2023-05-26 17:45
Duplicate of Michael Kalish's work with STLT dashboard. @mkalish

**Closed by bishoyayoub** 2023-05-26 17:45 UTC
Labels: pipeline, needs-refinement, API, platform
