### ISSUE TITLE
Consolidate the Report Enum on Sender and Report

### ISSUE THREAD

**Issue by mkalish** [CDCgov/prime-reportstream#14256] opened 2024-04-30 23:47 UTC
### User Story
As a developer on RS, I would like a consistent way to reference the format for a report.
### Description/Use Case
Currently,  there is both `Report.Format` and `Sender.Report` enums that reference the same values but can be used interchangeably in the code.

### Acceptance Criteria
- [ ] A single `Format` enum exists

**Comment by Andrey-Glazkv** [comment] 2024-06-03 15:33
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/14256?planning-poker) with Zenhub @adegolier @jalbinson

**Comment by Andrey-Glazkv** [comment] 2024-07-08 16:36
duplicate of #7656

**Closed by Andrey-Glazkv** 2024-07-08 16:36 UTC
Labels: platform
