### ISSUE TITLE
Osang LLC / Stone Labs Onboarding - Validate Test Files 

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#7090] opened 2022-10-21 16:13 UTC
### Acceptance Criteria 
- [x] Sample file from sender received by RS team 
- [x] Sample files saved to Keybase by assigned RS engineer 
- [x] Sample file ingested into RS using validation UI tool by assigned RS engineer 
- [x] Feedback provided to sender by assigned RS engineer  (including instructions on what to modify in order to get validated)* 
- [ ] Sender modifies and re-sends sample file to get file validated by RS engineer* 

*Steps can continue until RS can ingest the file from sender 

### To Do 
- [ ] RS engineer: update this ticket with comments with every interaction with sender 
- [ ] RS team member who originates this ticket: add any dependencies, as needed 
- [ ] RS team member who originates this ticket: complete the following when creating this Issue. 
     - [x] Pipelines: Onboarding & Operations (New) 
     - [x] Labels: "Onboarding-ops" and "Sender" 
     - [x] Epics: [select the epic for this API onboarding sender]

**Comment by BerniXiongA6** [comment] 2022-10-21 16:18
cc: @MauriceReeves-usds -- @jbiskie  is helping while you're out of the office -- we'll keep you posted on this when you return!

**Comment by jbiskie** [comment] 2022-10-21 22:31
Modifications requested:


Please use comma delimiters between fields. The sample you sent is tab delimited
The date fields are in scientific notation, so they've lost some precision. Please ensure you're sending the full date/time string.
One field was missing, testing_lab_specimen_received_date. This is in the spec between specimen_collection_date and test_result_date
date_result_release is missing the last letter, it should be date_result_released
The field testing_lab_clia should be either 00Z0000014 for OTC, 00Z0000015 for prescription
I noticed some ordering provider fields were filled in. If this was intended as a prescription, please also send the provider's NPI in ordering_provider_id. If this is OTC, leave all of the ordering provider fields blank.
patient_id: Our spec shows that this is optional, but as I was testing your file, I see that when it's omitted, it presents a problem for us with OTC. Can you provide a value here? If you don't have a true patient identifier, the same value that you're sending in the accession_number would work great.
patient_first_name and patient_last_name: I know you're omitting PHI for the sample, which is fine. Just a heads-up, you'll need to include a value when you actually test with the endpoint.
There are a number of extra fields in your file that are not necessary for OTC. Please omit the following fields:
patient_preferred_language
N/A
comment
test_result_status
testing_lab_name
testing_lab_street
testing_lab_street2
testing_lab_city
testing_lab_state
testing_lab_zip_code
testing_lab_phone_number
pregrant
employed_in_healthcare
resident_congregate_setting
residentce_type
hospitalized
icu
reporting_facility_name
reporting_facility_clia
ordering_facility_name
ordering_facility_street
ordering_facility_street2
ordering_facility_city
ordering_facility_state
ordering_facility_zip_code
ordering_facility_phone_number

**Comment by sliu1000** [comment] 2022-10-24 20:25
Update from Joel/Engineering:

Eric,

I've sent the API keys and sample commands to your keybase account.

Thanks!

Joel Biskie (Flexion, Inc.)
Integration Engineer
Pandemic-Ready Interoperability Modernization Effort (PRIME)

**Comment by BerniXiongA6** [comment] 2022-10-25 19:32
@jbiskie can pair with new engineer on this sender (OTC/CSV sender) cc: @BerniXiongA6

**Comment by jbiskie** [comment] 2022-10-26 18:33
From sender, 10/21:

> We appreciate your detailed feedback for the sample file and corrections.
> 
> Concerning each item, I'd like to add some firsthand comments or inquiries.
> (Please refer to text in blue)
> 
> Please use comma delimiters between fields. The sample you sent is tab delimited
>             -  We will correct this
> The date fields are in scientific notation, so they've lost some precision. Please ensure you're sending the full date/time string.
>             -  We will correct this
> One field was missing, testing_lab_specimen_received_date. This is in the spec between specimen_collection_date and test_result_date
>             -  We will correct this
> date_result_release is missing the last letter, it should be date_result_released
>             -  We will correct this
> The field testing_lab_clia should be either 00Z0000014 for OTC, 00Z0000015 for prescription
>             -  Considering the proper code again, 00Z0000015 should be the one for non-lab reporting use. 
> I noticed some ordering provider fields were filled in. If this was intended as a prescription, please also send the provider's NPI in ordering_provider_id. If this is OTC, leave all of the ordering provider fields blank.
>             - We will be working on this one.
> patient_id: Our spec shows that this is optional, but as I was testing your file, I see that when it's omitted, it presents a problem for us with OTC. Can you provide a value here? If you don't have a true patient identifier, the same value that you're sending in the accession_number would work great.
>             - We will fill in a value in the field.     
> patient_first_name and patient_last_name: I know you're omitting PHI for the sample, which is fine. Just a heads-up, you'll need to include a value when you actually test with the endpoint.
>             - We will fill in values in the fields. 
>                However,  one question is whether this is in accordance with "COVID-19 Pandemic Response, Laboratory Data Reporting: CARES Act Section 18115" ( https://www.cdc.gov/coronavirus/2019-ncov/downloads/lab/HHS-Laboratory-Reporting-Guidance-508.pdf)
>                On Page 6 of the document, there is a citation about de-identification and I wonder this doesn't have to be applied here.
> There are a number of extra fields in your file that are not necessary for OTC. Please omit the following fields:
>            - We will remove all those fields. 
> 
> 
> On the app, we'll shortly work on correcting all these at once on the mobile app and keep you apprised.

**Comment by BerniXiongA6** [comment] 2022-11-01 15:20
@BerniXiongA6 send emails to @brick-green cc: @oslynn

**Comment by BerniXiongA6** [comment] 2022-11-01 15:38
BX sent to Philip/Osang/StoneLabs on Nov. 1:
> Hi Philip,
> 
> We're assigning our engineer, Brick Green, to your team to help you finish onboarding to ReportStream. I've copied Brick in this email so you all can continue with validating the test files.
> 
> Thanks,
> Berni



From: Philip (ChoiJaeYoung) <jychoi3@osanghc.com>
Sent: Tuesday, November 1, 2022 9:19 AM

> 
>  
> Dear Berni,
> Thanks for prompt reaponse.
> Okay, we will wait for new member from your site.
> And now we are wondering whether CDC can check.the transmitted data through our mobile application(myHomeTest) or not.
> Should you check this data at your site, please inform us of that.
> Thanks and Best regards,
> Philip Choi

> Dear Joel,
> Thanks for your support and we remember your effort always.
> And I am wondering whethere CDC was received any reporting through "myHome Test" mobile application recently or not .
> We sent test results using our mobile application for validation.
> So, For registration of app on app store, we need to check whether CDC received our data successfully or not.
> I look forward to having your favorable reply soon.
> Thanks and Best regards,
> Philip Choi

**Comment by brick-green** [comment] 2022-11-02 14:47
We're receiving a bunch of files to staging but they only contain a single string: "Temporary_CSV_file.csv". It looks like Joel had requested changes but those changes had not yet been verified. So I requested that a new file be delivered to confirm the changes.

**Comment by shy2cdc** [comment] 2022-11-03 12:31
Email from Philip:

Dear Bernadette,
Thanks for your additional comment.
Dr Eric will back to you with finalized soon.
And then please check and let us know final validation result from your site.
Thanks and Best regards,
Philip Choi

**Comment by shy2cdc** [comment] 2022-11-04 12:03
Email from Philip:

Dear Brick,

Good day.

Thanks for your support and prompt response.

You are right. Actually today is our due date for submission and report of finalized mobile application “myHomeTest” development to FDA for COVID-19 antigen Self Test.

So, please support us,

 

I'm not sure if I should ask you following favors, but I'm inquiring because we have not enough time definitely. So, I'd appreciate it if you could give me your honest opinion.

Also, if you can share, we would like to show testing reporting example using “myHomeTest” application form such as following table until today.

Until next week, we will use “myHomeTest” mobile application only for verification and validation. After successful validation and approval of FDA, we will distribute this application to lay-users.

 

Also, If you should send us any approved letter or document for registration of Apple app. Store, it would be much appreciate.

We have submitted the “myHomeTest” mobile application for registration to Google plus and Apple app store with document for registration.

But both stores asked us any approved official certification by certified facility such as FDA or CDC for smooth registration process.

So, we shared authorization FDA EUA letter about OHC COVID-19 antigen Self Test with both stores and then both stores wanted to receive any approval letter or certified document about   “myHomeTest” mobile application for prompt registration on their stores.

So, it would be much appreciate to send us any document regarding agreement of “myHomeTest” mobile application for this mission.

 

 

Also I believe Dr. Eric will send you finalized revised test file for your review within today and we would like to receive your final approval.

 

 

Vendor Equipment Mapping

Equipment

IVD Test Mapping

IVD Test Performed

LOINC

MUST HAVE

MUST HAVE

MAY HAVE

MAY HAVE

MUST HAVE

MUST HAVE

MUST HAVE

MUST HAVE

MUST HAVE

MAY HAVE

MAY HAVE

MAY HAVE

MAY HAVE

MAY HAVE

MUST HAVE, IF LOINC populated

MUST HAVE, IF LOINC populated

MUST HAVE, IF LOINC populated

MUST HAVE, IF LOINC populated

MUST HAVE, IF LOINC populated

MUST HAVE, IF LOINC populated

MUST HAVE, IF LOINC populated

MUST HAVE, IF LOINC populated

MAY HAVE

Manufacturer

Model

Equipment UID

Equipment UID Type

Publication Version ID

Vendor Analyte Code

Vendor Analyte Name

Vendor Specimen Description

Vendor Result Description

Vendor Reference ID

Testkit UID

Testkit UID Type

Vendor Comment

LOINC Code

LOINC Long Name

Component

Property

Time

System

Scale

Method

LOINC Version ID

Testkit Name ID Type

OSANG LLC

OHC COVID-19 Antigen Self Test*

(Test kit device)

MNI

20220824

　

SARS-CoV-2 nucleocapsid protein antigen

anterior nasal (nares) swabs (697989009^Anterior nares swab^SCT)

COVID-19 POSITIVE (260373001^Detected^SCT)
COVID-19 NEGATIVE (260415000^Not Detected^SCT)
INVALID (455371000124106^Invalid result^SCT or 125154007^Specimen unsatisfactory for evaluation^SCT)

　

　

UDI

This test is also distributed under the brand name: • QuickFinder COVID-19 Antigen Self Test

97097-0

SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay

SARS coronavirus 2 Ag

PrThr

Pt

Respiratory.upper

Ord

IA.rapid

2.70

EUA

 

 

I look forward to having your favorable reply soon.

Thanks & Best regards,

Philip Choi

**Comment by sliu1000** [comment] 2022-11-17 19:50
Update from Osang:

Dear Green,
Good day.
Our Engineer has finalized all cording work about application now. So, please check csv once again.
If you had not receive any full data yet, maybe Completed 2D barcode on our test cassette has not released yet.

But it would be appreciate to share any expected our problem with me and Dr Farid if you know. 

I look forward to having your favorble reply soon.
Thanks and Best regards,
Philip Choi

**Comment by sliu1000** [comment] 2022-11-17 19:51
@oslynn Here's the sender that needs help while Brick is out.

**Comment by BerniXiongA6** [comment] 2022-11-17 20:14
@oslynn @sliu1000 I"ll be reaching out to the sender to let them know they can validate their test files using SimpleReport's validation tool. I'll make sure to cc: you both.

**Comment by BerniXiongA6** [comment] 2022-11-17 21:06
Quick update for all, I'm in talks with SimpleReport right now and so far I'm learning that the CSV validation tool is not currently leveraged as a standalone service, I'll find out more from Zedd to confirm that. Then, I'll inform Osang of next steps whether they can use CSV validation tool or not. Thanks! @oslynn @sliu1000

**Comment by BerniXiongA6** [comment] 2022-11-17 22:30
Hi @oslynn  and @sliu1000 -- Quick update on some investigation I did:

1. I confirmed from SimpleReport that their CSV validation tool is not a standalone feature for users
2. I confirmed from kevinh that SR’s validator is effectively only validating against the simple_report organization in ReportStream. Since ReportStream senders will be their own unique organization, SR’s logic would not suffice UNLESS the incoming sender uses the exact same CSV schema as SR.

All that being said, I'll make an email introduction between Ott and Osang's technical contact so that Ott can continue where Brick left off and the progress on validating their test files.

Thanks for stepping in, Ott!
cc: @brandonnava

**Comment by oslynn** [comment] 2022-12-13 15:30
Question from OSANG LLC:

1.) Can you share our company how many results of the Self Test of COVID-19 are reported 
through the mobile application in USA per day or per month approximately?

2.) If you could make me know how to way to roughly figure out the reported quantity 
through mobile application about COVID-19 Antigen Self Test, it would be much 
appreciate and helpful for us.

**Comment by brandonnava** [comment] 2023-01-17 19:11
@oslynn to follow up based on their response of being un-proctored

**Comment by oslynn** [comment] 2023-03-06 20:08
They never response back to email. I will close it for now. We can reopen it when they are ready to continue.

**Closed by oslynn** 2023-03-06 20:08 UTC
Labels: onboarding-ops, sender
