### ISSUE TITLE
Receiver facing: show PHD which facilities' data are included in state's single data connection

### ISSUE THREAD

**Issue by BerniXiongA6** [CDCgov/prime-reportstream#4759] opened 2022-03-14 16:38 UTC
## Problem statement

As a public health department, I want to know which facilities' data are included in the state's single data connection so I can track which facilities and organizations are able to submit data to us.

## What you need to know
- This came from [Issue 4527](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4527)

## Acceptance criteria

- [ ] ...

## To do

- [ ] ...

**Comment by drew-usds** [comment] 2022-12-19 17:49
Closing. Duplicate of @fmccaf1 's current work.

**Closed by drew-usds** 2022-12-19 17:49 UTC
Labels: experience, needs-refinement
