### ISSUE TITLE
WA - Certificate Expiration

### ISSUE THREAD

**Issue by shy2cdc** [CDCgov/prime-reportstream#6199] opened 2022-07-21 19:03 UTC
WA DOH - Jennifer Risler - jenni.risler@doh.wa.gov

WA OneHealth Port certificate expiration issue.  USDS contacted WA DOH about submission errors related to certificate expiration.  Service was interrupted between 7/9 and 7/15.  Certificate issues resolved 7/15, but we are missing records generated during the service interruption.  Requesting USDS reprocess messages that failed to send between 7/9/2022 and 7/15/2022.

**Comment by brick-green** [comment] 2022-07-21 23:05
ReportIDs for the the primary feed:
```
72e9c3d6-2a68-4f13-9f6a-0eb4e4f3f10d
b7dd795b-4614-4e74-9407-9b26eaf0493f
1502c10a-c607-4f3b-b769-e7293e06b1fa
a68d7553-b671-4102-a432-e10acf87772b
19c8bd33-674a-4c79-94a0-257ed0e65878
a8ce78ac-bb13-4cb9-9072-d1503ba0a58f
dae8cbb9-69a9-413d-b093-0a35ff5fadf4
b7d8f279-80a1-4afd-9ed2-cc51d7fdcb59
ecf4b8bb-4df9-49eb-b518-8a2178ff3400
69bf16ee-482d-4c06-9421-91096d04496f
0488c070-f1e4-4073-9e66-912c8b5c1fd2
95c9bcd8-c720-44b0-9fc2-850603bf222a
eff7abb3-2dfe-4776-9f3e-1408f806404f
bbd3ecb3-bbf5-48b1-8be3-e010748755dc
15e767ae-f4d9-40f0-bc92-a9af831e31c7
2c95b130-008f-444a-82e4-eaebb2baa99c
6737d133-79cc-4eab-8680-55617553dbcd
f09cf7bd-4345-4913-9da2-73e1f2e9d171
57e6e8e8-7e34-4e2e-8326-42ff632eeea7
c283c2da-099f-4487-94e6-922eb4f796c7
220dea3e-7464-4b80-842b-e46308ebfe5e
be920c8d-aac2-4ba1-bccd-bb5a47f2f69f
22d368e8-7176-4869-8a3d-ca90cc10bad1
67609b07-2a84-4d62-9591-d0388a2fec64
b59f116e-90e1-4154-b38f-e8527f076751
a5e5649a-bffa-4265-8427-84f40a187b43
969ee2f6-7744-43fe-ba72-c0c85fb7c59a
251b26c4-4967-473a-93c8-53555fcfec42
2d8414a6-7b3b-49cf-9d60-91b1958655de
92f5fadf-4ff7-4674-8945-e64d6c6ddf42
eb1fd98c-f4d5-4b6d-967e-a00eca453cae
9c1204fe-528d-4069-8212-2f77b7c2a689
b276af49-080c-4acd-9bf1-4788e9eae75b
b32f6dd1-8a73-4568-bb7c-06b3d750cb2a
ab4188aa-d14a-45e2-8e93-54a5e88ca1b0
4838c48b-6452-4a7d-b39f-48df76126962
8f17e61e-054a-4b8f-b79a-e791e278efdd
a7b43eb0-9060-4600-ba41-7d33583af337
4c58c269-5c04-447c-ab3b-209687b8433b
c2fff679-e2aa-4ed3-a5b2-996f57680cc7
e46d634c-a131-4908-9ff3-6a36337503a1
b2c2adc1-7813-45a3-a18b-83c0a62e5bfa
52a53b31-caa0-4af6-9a06-5161845276bb
e8d8ab59-8f58-4ea4-85d9-aa1923ec2b7a
76476205-a709-46e4-94ea-1e56e6d4c089
81c86042-6ea7-4061-a617-18a88175f8fa
fe617751-688a-4d5c-a27a-7dd512838bbe
dcfaff9b-871d-4f8e-ba5f-3454fadf6fd8
757cfe68-8142-4c08-be8c-723ae394f915
13f1d667-7d2c-4a89-856e-d8a46b76e607
fab45f8f-5fb1-494d-ad03-7f5d38b2a36a
220098ac-151a-4c2c-84d8-868363b1feb6
```

**Comment by brick-green** [comment] 2022-07-21 23:06
ReportIDs for the negative feed:
```
3ed48720-c232-46f5-93b4-a5a90b8d3d58
6bab3e4c-d628-44a0-a0a3-05aec6bcc190
896efdb2-1257-4c59-b526-75a0c589c90a
4bde137f-56aa-4d55-a576-43e5cc4709dc
7a547dad-f6e9-4bbc-b547-376a77cb6bd4
d955ab4e-050c-40a7-9034-6ec062cf63f4
87f018e4-459f-472d-8e4a-7bb6d231fa07
b8e060bb-8dfd-4b03-a839-ebadd8ca7715
9152b9eb-509a-4ffe-aecf-6e05b2b7cc68
cee8c6ca-1545-4d8d-8869-ce11694efa52
8a7c9712-4cb5-4cde-b617-ae2f99a99368
36344846-15e2-43f8-a3ac-437b50448895
3baccba2-26ea-4f5e-bcf4-ad565d520b8e
31e9cdd5-fe68-48e4-bd8f-4b8958531d4c
2fcc5e8c-f33e-4211-a7f5-58a6d611833c
602f81f2-5026-4ca0-aa98-b6d2e0cde629
d76bf8e9-833a-4c0b-9dfc-f28f3125542a
7d9e9440-a4c5-45e8-8970-b46ff151a970
53baea52-cc81-471d-b298-5b5d58345a8d
5be439ff-24a3-4636-9456-7f3f0210e90f
c0cd4a97-727c-4dd5-8318-41068b724227
be5bdca4-5dae-465f-b49e-39fdcbaa53ab
b4d98f18-e0d5-466b-b8cb-caed137ca57f
c2516567-1b3c-4a48-a3c0-53cf2b7d7552
c26c1e04-c253-4ab3-8cc0-a2668bd625e4
18c01a74-cafd-4a3a-8983-fd2cd105f04e
a8107795-18b4-447d-bc2f-56613065c07b
cfd758f6-7a57-40ed-8981-e3cb800552ff
84cc60c6-d622-4e5a-b982-628e5c5e0b0b
2f437015-afdd-47b3-b2e1-92a92ce3f890
1a93d973-2541-47cf-9f95-bca31836de4e
2d4f1ab4-090f-41d7-808c-dfc3477e79ab
42eb07dd-b2df-4509-b999-c9eb8adccbbb
9bfbdb97-a7e4-495f-bafb-f1fcd5b81c45
551e2928-7f70-4225-9d12-0f448c5c9323
8615f35e-0849-4c1c-af43-313781077650
03da400e-a59f-4b33-be83-da40e8e26da9
5ab9b0a3-b2b9-435d-a08f-7596e7e8fb0e
1b802bb7-f73f-45c0-84d6-c0142d625659
db7d32bb-ff73-4539-84d1-ff522af7bd82
73a92229-e3d8-4633-b66b-0d4ade5e2fb0
be37df5f-f72c-4389-8230-711de50c678d
53af89c9-b9fb-442a-a9ae-c41e383694b7
5b404399-2721-499e-82aa-d5a6742e34fa
a243d744-98d6-41a8-82ca-3b4dbccc1616
435637d6-cc37-4518-bba8-5b97741af0e3
933bea90-6c8d-4483-a23e-cd3c339f4018
56341e36-9392-4d04-8635-96d40d6087a0
79ac54a7-47f3-488a-bcbd-d6b98b7bcbdb
20892941-8f15-45fb-ba0e-37be1d58e55a
8a359291-842c-4a5d-9862-905840f8d062
77ba6f9a-dac4-42e3-a6cd-5a9aaca98147
352ec0fd-18a3-493f-a407-4ffbca7d8ff6
f40606e5-c57a-4a89-aa62-65388bb4502d
f7389757-fcf8-462e-8bae-9848fe8fc817
c74a0976-b989-4ebc-8a55-da89a3428c76
4e74ccc6-55b5-4cfd-9e78-cc6182e0b13a
a859c8fa-70c3-4272-9f0f-82fec92cf34e
5a30d124-7b86-4a94-9d64-47050fe49f8f
da8d01f8-9964-4fb8-81ab-a66f6d447205
a0805ce2-4312-4414-9031-b090187292c3
6dc24f3f-8267-4940-b71f-e864dce54f52
176d310e-f707-41ed-b5e3-f9f4214af38f
edf06af8-00a5-4e56-aaf8-3ece80c1cb8a
8d214056-b073-4dd5-90d9-2b59fa1f3a71
3343d64c-dba2-484d-b36c-faeaeaeb22e4
0c865dfa-a494-4511-9ccc-37a9d53cd29f
d8c2cc47-8aa7-4cc1-b17a-e9a98a36c9a1
7cb59b28-070e-4452-970a-b833e27e7f92
```

**Comment by brick-green** [comment] 2022-07-21 23:07
Those are for reference in case. But the easiest option is to go into azure blobstorage and download all files from the two feeds that were created 7/9-7/15. Then they can be manually transferred.

**Comment by sliu1000** [comment] 2022-07-22 19:31
@brick-green Hi Brick, I'm working on getting read only access to the blobstorage. Who should we assign this ticket to?

**Comment by brick-green** [comment] 2022-08-08 18:56
I completed the resend of these results.

@sliu1000 I'm struggling a bit to grab the messageID or filename list. There's just not a good way to query for it. Can you let WA know this is complete? 

If they ask for the filenames to verify against then I may be able to go into blob store and copy/paste them from there. But I don't want to spend that time unless WA needs them.

**Comment by sliu1000** [comment] 2022-08-08 19:07
@brick-green Hi Brick,  I have emailed Jenni and cc'd you as well. Will keep you posted if she requests anything else on this.

**Comment by BerniXiongA6** [comment] 2022-08-08 20:52
Hey @brick-green looks like WA (Jenni) is now requesting filenames. Can you help? cc: @sliu1000

**Comment by brick-green** [comment] 2022-08-09 15:09
@BerniXiongA6 Yep yep, here's the list:
[WA Filenames 7:9 - 7:15.csv](https://github.com/CDCgov/prime-reportstream/files/9292218/WA.Filenames.7.9.-.7.15.csv)

**Comment by BerniXiongA6** [comment] 2022-08-10 16:05
Per Jenni: "Thank you Berni, I can confirm that we received these files.  We are ready to close this issue."

 

Best,

Jenni

**Closed by BerniXiongA6** 2022-08-10 16:05 UTC
Labels: onboarding-ops, High Priority, Washington, Resubmissions Required
