### ISSUE TITLE
Rename API endpoint sortCol parameter

### ISSUE THREAD

**Issue by TurkeyFried** [CDCgov/prime-reportstream#6146] opened 2022-07-18 15:13 UTC
As an user of the ReportStream API, I want the parameters I can use when browsing to clearly define their functionality.

### Description/Use Case
The parameter of `sortCol` doesn't accurately describe the purpose it has. It needs a new name.

### Risks/Impacts/Considerations
Some users are already working with the `sortCol` parameter. A deprecation period will be needed.

### Dev Notes:
`sortField` is a good choice for a new name.

### Acceptance Criteria
- Queries that use `sortCol` work exactly the same when that field is replaced with the new name.
- `sortCol` still works.

**Comment by bishoyayoub** [comment] 2023-05-26 17:51
Duplicate of @mkalish work on STLT dashboards.

**Closed by bishoyayoub** 2023-05-26 17:51 UTC
Labels: pipeline, tech-debt, platform
