### ISSUE TITLE
Bug when trying to view delivery details for reports that are not batched but sent as single messages

### ISSUE THREAD

**Issue by GilmoreA6** [CDCgov/prime-reportstream#14127] opened 2024-04-19 21:09 UTC
### User Story
As a receiver who has useBatchHeaders set to false. I want to be able to see my reports in Daily Data without errors. 

### Description/Use Case
When there are multiple reports sent to a receiver at the exact same time (which occurs when there is a receiver not using batch headers, but is instead receiving each message as it's own report). The delivery details link returns a 500 error with the exception:

"org.jooq.exception.TooManyRowsException Message: Cursor returned more than one result"

This can by observed logging in as ar-phd in prod, going to [Daily Data](https://reportstream.cdc.gov/daily-data), and then selecting the "reportID" link to see more details for report_ID "18955639-1c6d-4182-a078-f91f6ecbdc25"

### Dev Notes
This occurs because the query in the fetchAction method in the DatabaseDeliveryAccess class throws an exception because there is more than one report with the same action id.

### Acceptance Criteria
- [ ] The delivery details page loads for reports that originated from a report with multiple messages to a receiver who has useBatchheaders set to false.
- [ ] The fetchAction method can handle the situation where there are multiple reports returned OR multiple reports being returned are eliminated as a possibility.

**Comment by JessicaWNava** [comment] 2024-06-04 16:11
Updated to the new description to pass off to Platform before realizing I could not just move the ticket over to their board. Created the ticket here https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/14609 Will be passing this work off to them for them to decide on a solution now that the problem is found. Closing out this ticket.

**Closed by JessicaWNava** 2024-06-04 16:11 UTC
Labels: bug, onboarding-ops
