### ISSUE TITLE
MD - Filter Out CAREEVOLUTION results

### ISSUE THREAD

**Issue by rnz6** [CDCgov/prime-reportstream#9985] opened 2023-06-16 19:50 UTC
## Problem statement
*Kristy Lunquest - kristy.lunquest@maryland.gov*
*User states*

Is it possible to also filter out CAREEVOLUTION results? They are not reporting patient names or DOB.

ex. f89bbd5d476a44efba7bd8b6c60148ec
ac6ae52b44084c51aff69c079b325c74
33de94ff442d49dcbe4dfb485a6a0a0c
807d2343c7e94d04bdf2c136090f0844
aa8fcb2a7e6d4548ae5752b4fae45c4c
c99cf3ffcf104a7f9225e5a59c73290b
8c49d6fcd6c34345b1bf7f446ae126cb
5898fb5cf1a74c6c9ecce360c53cb3c1

## What you need to know

They are not reporting patient names or DOB.

## To do

Filter out results

**Comment by LaFreda1** [comment] 2023-06-22 17:08
I just assigned this to Kant a day ago @sliu1000. @kant777  will you move this ticket up in your list of priorities? I have labeled it as high. Thanks!

**Comment by sliu1000** [comment] 2023-07-12 15:11
@kant777 @LaFreda1 Hi Kant, any update on this? Kristy from MD is still receiving the CARE-evolution results.  See below her comments:

Hello,

I wanted to check on this ticket. We are still receiving CAREEVOLUTION results.

Thanks,
Kristy

On Fri, Jun 16, 2023 at 3:53 PM Report Stream (CDC) <reportstream@cdc.gov> wrote:
Hi Kristy,

Thank you for contacting ReportStream Support.

We have received your inquiry and created a ticket #9985 for the engineers to review. We will get back to you with an update as soon as possible. 

Thank you,

**Comment by GilmoreA6** [comment] 2023-07-13 19:04
@sliu1000 Can you repost the examples in the ticket? It looks like they got formatted weirdly when they were pasted in and so it's making it difficult to search for those examples

**Comment by sliu1000** [comment] 2023-07-13 19:40
@GilmoreA6 Its coming from Intrivo. They said that they have found 128 results not many but consistently sending 10-20 a month since October 2022. All have names as "unknown".

**Comment by GilmoreA6** [comment] 2023-07-13 20:17
@kant777 This should help. I'm pretty certain then that the issue is that secondary receiver since the primary receiver has a quality filter for "unknown" in patient name fields. It that is the case we would have to modify the logic on the secondary receiver to exclude patient names of "unknown,Unknown or UNKNOWN" like we are in the primary receiver

**Comment by GilmoreA6** [comment] 2023-07-13 20:17
@kant777 This should help. I'm pretty certain then that the issue is that secondary receiver since the primary receiver has a quality filter for "unknown" in patient name fields. It that is the case we would have to modify the logic on the secondary receiver to exclude patient names of "unknown,Unknown or UNKNOWN" like we are in the primary receiver

**Comment by kant777** [comment] 2023-07-14 04:55
@GilmoreA6 The primary ones have the following filters and the secondary receiver has no quality filter at all. Just looking at the filters below it appears like I have to apply all of the filters in this case?

```
[
  "doesNotMatch(patient_city,Unknown, unknown, UNKNOWN)",
  "doesNotMatch(patient_first_name,Unknown, unknown, UNKNOWN)",
  "doesNotMatch(patient_last_name,Unknown, unknown, UNKNOWN)",
  "doesNotMatch(patient_state,Unknown, unknown, UNKNOWN)",
  "doesNotMatch(processing_mode_code,T,D)",
  "hasAtLeastOneOf(order_test_date,specimen_collection_date_time,test_result_date)",
  "hasAtLeastOneOf(patient_street,patient_zip_code,patient_phone_number,patient_email)",
  "hasValidDataFor(message_id,equipment_model_name,specimen_type,test_result,patient_last_name,patient_first_name,patient_dob,patient_city,patient_state)",
  "isValidCLIA(testing_lab_clia,reporting_facility_clia)"
]
```

**Closed** 2023-07-14 17:51 UTC
Labels: onboarding-ops, High Priority, Maryland
