### ISSUE TITLE
CA - Poorly Formatted Accession Number

### ISSUE THREAD

**Issue by Jcavallo7** [CDCgov/prime-reportstream#7689] opened 2022-12-14 23:10 UTC
User states: Hello, we have received a set of report that have an incorrect / poorly formatted accession number. I did a quick review and it looks like these are from Gaslamp Medical Center 250 Market St, San Diego CAn92101 USA.

Please correct and resend the reports for the affected messages." 

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/93fa0b50-33ab-4a2b-be66-76dde40e3be6)

Me and Sharon proceeded to conduct research and responded to the user " possible that during the conversion on your end it created the shortform version you are seeing" 

![image.png](https://images.zenhubusercontent.com/62828ac9597e3bae41382df7/211ed95b-2c09-47df-bdbe-617653fc4e8c)

**Comment by brick-green** [comment] 2022-12-29 15:24
That value is typically provided by the sender. We wouldn't be doing any alteration. The work here would be to double check that the value we're sending is exactly the same as what was sent to CA. If it is, then we relay that info to CA. If it isn't then we need to do additional investigation into why it's not the same.

**Comment by BerniXiongA6** [comment] 2022-12-29 16:20
@BerniXiongA6 check with sender (according to Brick's recommendation) and then follow up with CA. cc: @sliu1000

**Comment by BerniXiongA6** [comment] 2022-12-29 23:20
Hey @Jcavallo7 @sliu1000 -- I've tried to find the originating email from the sender but there's nothing in the RS shared inbox. Did this come from the SR shared inbox? Could you provide our team with the sender's info? We'd like to start working on the ticket in this coming sprint and we'll need to reach out to the sender to ask follow up questions. Thank you! cc: @brick-green @brandonnava

**Comment by Jcavallo7** [comment] 2022-12-30 00:41
Hey @BerniXiongA6 it came in through the simple report box, apologies if I neglected that detail. Here are the original senders info: 
Jill Meesey (jill.meesey@cdph.ca.gov)
Marjorie Richardson (marjorie.richardson@sdcounty.ca.gov)

**Comment by BerniXiongA6** [comment] 2022-12-30 15:45
BX sent email to original requesters of this ticket on 12/30:
> Hi Jill and Marjorie Richardson,
> 
> Our operations team here at ReportStream will be bringing ticket (# 7689) into our upcoming work. In order to troubleshoot, we'll need to know what the Accession numbers are so we can confirm whether ReportStream is receiving the correct values from Gaslamp Medical Center that we are passing through to public health. 
> 
> Can either of you confirm what the Accession numbers should be for this request? I'm attaching the screenshot that we received with the original request.
> 
> 
>  
> Once we receive this information, that can help our team identify what could be happening and determine how to fix this issue.
> 
> Thanks,
> Berni

**Comment by BerniXiongA6** [comment] 2022-12-30 19:05
BX send email to sending facility (since Jill and Marjorie are the receivers) on 12/30:

> clinic@gaslampmedicalcenter.com
> Report Stream (CDC);Green, Brick (CDC/DDPHSS/OD/HITSSU) (CTR)
> Hello Gas Lamp Medical Center Team:
> 
> Our operations team here at ReportStream received a request from your public health authority to troubleshoot an issue regarding COVID-19 data that was submitted to ReportStream with incorrect Accession numbers—which failed validation at your jurisdiction. 
> 
> In order to investigate this further on the ReportStream end, we'll need to know what the Accession numbers are for the records that are included in this screenshot shared with us by your public health authority. Once we know what the correct Accession numbers should've been submitted to ReportStream, that will allow us to verify whether ReportStream is receiving the correct values from Gaslamp Medical Center that we are passing through to public health. 
> 
> Can your team confirm what the Accession numbers should be for the following messages? 
> 
> 
>  
> 
> Thanks,
> Berni
>

**Comment by BerniXiongA6** [comment] 2023-01-17 17:54
@brandonnava fyi

**Comment by brandonnava** [comment] 2023-01-31 19:35
@Jcavallo7 @sliu1000 Since this came from SR, can you or someone on the SR side follow up with them?

**Comment by sliu1000** [comment] 2023-02-01 18:49
@TaneaY Do you mind looking into this further.

**Comment by TaneaY** [comment] 2023-02-01 22:32
@sliu1000 Follow-up email sent to requestor jill.meesey@cdph.ca.gov and submitter clinic@gaslampmedicalcenter.com as I do not see a reply from either for additional information. Prior research of file received on 12/14 shows that CA DPH was sent an HL7 file in the correct format. ![image.png](https://images.zenhubusercontent.com/628286bc0129e14bd536e6f9/b6e4cb24-9192-40ad-b3de-ed52b3e44f06)

**Comment by sliu1000** [comment] 2023-02-08 02:00
@brandonnava 

Receiver - Jill from California is requesting for the "expanded format" to be used for files being sent to CA as it's causing parsing issues on their side:  See below the specific response:
------------------------------[https://app.zenhub.com/files/304423150/44837246-5615-441a-a5e0-e6b7d3587152/download](https://app.zenhub.com/files/304423150/44837246-5615-441a-a5e0-e6b7d3587152/download)-
Hi Tanea, I apologize for my confusion. I was busy last week. I don’t believe the December issue was resolved. And the issue is still happening. Any of the shortened scientific numbers that are the same, will attach to the first instance of the number coming across since accession number is one of our primary matching metrics.

Just going back to 12/1/22, there are 2466 entries with scientific format instead of the expanded number. Many of these have repeated values causing multiple different people to be attached together.

Please escalate this issue to be fixed and resubmitted.  

In column H and I, I have highlighted three sets of accession number all for different people that have been attached to each other.

**Comment by sliu1000** [comment] 2023-02-21 21:06
Emailed Jill for an updated example - as the one that is referenced is older than 60 days.

**Comment by sliu1000** [comment] 2023-02-22 00:23
@oslynn Receiver sent over new examples

Please see attached for the accession numbers:
(https://app.zenhub.com/files/304423150/273343fa-3355-4b61-b19d-b85f313970b3/download)

Hi Sharon, here is a list for February. The two examples below are from today.

Shortened and causing reports for different people to attach to each other:

SPM|1|1.67683E+15 & Action Urgent Care I & 05D2078131&CLIA^1.67683E+15 & Action Urgent Care I

Expanded and unique:

SPM|1|1c807a03-f24a-49b6-8f02-36e7eef3bbb5&Torrance Memorial&05D0642594&CLIA^1c807a03-f24a-49b6-8f02-36e7eef3bbb5&Torrance Memorial&05D0642594&CLIA||

**Comment by oslynn** [comment] 2023-02-22 21:01
After looking at the messages from SimpleReport.  I think the sender uploaded CSV file produced by excel that has Format Cells -> Number -> Decimal places set to [ 2 ].  This will automatically be set to a large number in engineering number format (i.e. 1234E+15).

**Comment by oslynn** [comment] 2023-02-22 21:04
@sliu1000  I need to get with SimpleReport folk to see the csv file that was uploaded to them.

**Comment by sliu1000** [comment] 2023-02-22 22:27
Email sent to SimpleReport Lab:

Hi Noah,

CA State is having issues with reviewing your labs Accession Numbers for 2/21/2023.  Can you please advise on the format you are using when you submit your CSV files via SimpleReport?  Perhaps you can send us a sample file so we can see what format you are using.   Please DO NOT sent any PII/PHI.  You can just delete those columns from your file.

Best regards,

Sharon

The ReportStream Support Team

Contact us at [reportstream@cdc.gov](mailto:reportstream@cdc.gov)

Support hours:  8:00 am through 9:00 pm Eastern time

Monday-Friday, excluding US public holidays

**Comment by oslynn** [comment] 2023-02-23 18:55
Sender used Excel or Spreadsheet software to generate the CSV file to upload to SimpleReport.  That software has default Format Cells to Number Decimal places of 2.  Therefore when they save the file, it saves to the engineering format for a large number that has 12 digits or more (i.e 123456789012 save to 123457E+11).

To fix this, the sender needs to reformat all Cells to Number Decimal places of 0 as following step with MS Excell:
  1.) Press Ctrl + A to select all cells
  2.) Right-click on the mouse.
  3,) Select Format Cells
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/0d04af6d-f7ac-448a-b455-9326207bbf24)

4.) Select Number -> Decimal place -> 0
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/188af7af-d2e9-4cf6-9111-8e21d4931a15)
5.) Press OK
6.) Save the file.

**Comment by sliu1000** [comment] 2023-02-23 19:38
@oslynn I sent the email and cc'd you.

**Comment by oslynn** [comment] 2023-02-23 20:20
@sliu1000 for Google Sheets do the following:
1.) Crtl + A to select all cells
2.) Mouse click on **123** as a screenshot and select **Custom number format**
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/0d94e94a-876b-46f5-8536-be02bc1b1129)
3.) Select **0** and **Apply**
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/a698048f-2b57-4bc0-809e-be129a328c93)
4.) File -> Download -> Comma Separated Values (.csv)
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/a2aac2c2-442a-4bf8-9d59-f405f62127df)

Screenshot before:
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/f48f8d85-0ce9-4b76-a055-8b4bcfc76677)

Screenshot after:
![image.png](https://images.zenhubusercontent.com/6166db74c72e6d9735fd8b3b/7ab5eec2-0781-4e1e-9798-734e05830458)

**Comment by oslynn** [comment] 2023-02-23 20:26
I am closing this ticket: Done.

**Closed by oslynn** 2023-02-23 20:26 UTC
Labels: onboarding-ops, support, California
