### ISSUE TITLE
Create converter to change FHIR file back to internal csv

### ISSUE THREAD

**Issue by clediggins-usds** [CDCgov/prime-reportstream#2685] opened 2021-10-20 17:33 UTC
Build a process that converts our internal FHIR format into our internal CSV format. This will eventually be throwaway code but will be used in the meantime to verify our FHIR generation, and will help us move from storing internal CSV at all. Intent is to replace internal CSV storage with FHIR, and use this converter to go back to internal CSV for processing until we replace the processing step.

**Comment by JGreenFearless** [comment] 2022-02-02 17:36
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pipeline-6182b02547c1130010f459db/issues/CDCgov/prime-reportstream/2685?planning-poker) with ZenHub @carlosfelix2 @jh765 @jimduff-usds @oslynn @smythe5 @whytheplatypus

**Comment by jimduff-usds** [comment] 2022-03-22 17:38
Duplicate of other tickets.  Closing.

**Closed by jimduff-usds** 2022-03-22 17:38 UTC
Labels: pipeline, fhir
