### ISSUE TITLE
Update to Node 18

### ISSUE THREAD

**Issue by kevinhaube** [CDCgov/prime-reportstream#7078] opened 2022-10-20 16:52 UTC
## Problem statement

Node 16 LTS ends **September 11, 2023**. Our current node required version is `16.18.0`. We will need to update the app and CI to run on Node 18 by the end of Node 16 LTS.

## What you need to know

- [Node EOL (end of life)](https://endoflife.date/nodejs)
- Using NVM (Node version manager) that has some info you may need to know

## Acceptance criteria

- [ ] ReportStream's front end requires Node 18.x.x
- [ ] Github Actions frontend-build requires Node 18.x.x
- [ ] Update the .nvmrc

## To do

- [ ] ...

**Comment by stephenkao** [comment] 2022-12-14 17:50
We'll likely want to upgrade react-uswds to at least 3.1.0 prior to this since that's the first version that supports Node v18 as an engine: https://github.com/trussworks/react-uswds/compare/3.0.2...3.1.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L20

**Comment by chris-kuryak** [comment] 2023-01-20 16:09
Blocked by react USWDS update.

**Comment by stephenkao** [comment] 2023-01-25 22:19
react-uswds upgrade was merged last week so this ticket is unblocked now!

**Comment by kevinhaube** [comment] 2023-01-26 20:08
https://github.com/CDCgov/prime-reportstream/pull/7817/files

**Comment by jpandersen87** [comment] 2023-01-30 21:00
There's potential proxy issues with the move that @stephenkao noticed but not confirmed to be a bug for this transition. However, this ticket is blocked by https://github.com/mswjs/msw/issues/1388 (will not be trying workaround mentioned here: https://github.com/mswjs/interceptors/pull/283#issuecomment-1333954204).

**Comment by jpandersen87** [comment] 2023-03-07 01:46
Post-CRA ejection, it is now more obvious that we are polyfilling fetch with whatcg-fetch so we are in fact not blocked with node 18 compatibility. When msw is updated to support node 18 we can drop the polyfill.

**Closed** 2023-03-10 17:34 UTC
Labels: experience, engineering
